NORMAL_EXIT = 0x000000
SECRET_EXIT = 0x100000
DRAGON_COINS = 0x300000
MOON = 0x400000
HIDDEN = 0x500000
CHECKPOINT = 0x600000
PRIZE = 0x700000
ROOM = 0x800000
ENEMY = 0x900000
BLOCK = 0xA00000
GOAL = 0xF00000

YI1 = 0x29000000
YI2 = 0x2A000000
YI3 = 0x27000000
YI4 = 0x26000000
YIC = 0x25000000
YSP = 0x14000000

DP1 = 0x15000000
DP2 = 0x09000000
DP3 = 0x05000000
DP4 = 0x06000000
DS1 = 0x0A000000
DS2 = 0x2F000000
DGH = 0x04000000
DSH = 0x13000000
DPC = 0x07000000
GSP = 0x08000000

VD1 = 0x3E000000
VD2 = 0x3C000000
VD3 = 0x2E000000
VD4 = 0x3D000000
VS1 = 0x2D000000
VS2 = 0x01000000
VS3 = 0x02000000
VDH = 0x2B000000
VDF = 0x0B000000
VDC = 0x40000000
RSP = 0x3F000000

BB1 = 0x0C000000
BB2 = 0x0D000000
CBA = 0x0F000000
COM = 0x10000000
SOL = 0x11000000
TWC = 0x0E000000

FI1 = 0x42000000
FI2 = 0x44000000
FI3 = 0x47000000
FI4 = 0x43000000
FGH = 0x41000000
FSA = 0x46000000
FIF = 0x1F000000
FIC = 0x20000000
BSP = 0x45000000

CI1 = 0x22000000
CI2 = 0x24000000
CI3 = 0x23000000
CI4 = 0x1D000000
CI5 = 0x1C000000
CGH = 0x21000000
CSA = 0x3B000000
CIF = 0x1B000000
CIC = 0x1A000000

SGS = 0x18000000

VB1 = 0x3A000000
VB2 = 0x39000000
VB3 = 0x37000000
VB4 = 0x33000000
VBH = 0x38000000
VBF = 0x35000000
VBC = 0x34000000

SR1 = 0x58000000
SR2 = 0x54000000
SR3 = 0x56000000
SR4 = 0x59000000
SR5 = 0x5A000000

SZ1 = 0x4E000000
SZ2 = 0x4F000000
SZ3 = 0x50000000
SZ4 = 0x51000000
SZ5 = 0x4C000000
SZ6 = 0x4B000000
SZ7 = 0x4A000000
SZ8 = 0x49000000

LOCATION_MAPPING = {
    [NORMAL_EXIT | YI1] = {"@Exits/YI1/Normal Exit"},
    [NORMAL_EXIT | YI2] = {"@Exits/YI2/Normal Exit"},
    [NORMAL_EXIT | YI3] = {"@Exits/YI3/Normal Exit"},
    [NORMAL_EXIT | YI4] = {"@Exits/YI4/Normal Exit"},
    [NORMAL_EXIT | YIC] = {"@Exits/YIC/Normal Exit"},
    [NORMAL_EXIT | YSP] = {"@Exits/YSP/Normal Exit"},
    [NORMAL_EXIT | DP1] = {"@Exits/DP1/Normal Exit","@Exits/DP1/Swapped Normal Exit"},
    [SECRET_EXIT | DP1] = {"@Exits/DP1/Secret Exit","@Exits/DP1/Swapped Secret Exit"},
    [NORMAL_EXIT | DP2] = {"@Exits/DP2/Normal Exit","@Exits/DP2/Swapped Normal Exit"},
    [SECRET_EXIT | DP2] = {"@Exits/DP2/Secret Exit","@Exits/DP2/Swapped Secret Exit"},
    [NORMAL_EXIT | DP3] = {"@Exits/DP3/Normal Exit"},
    [NORMAL_EXIT | DP4] = {"@Exits/DP4/Normal Exit"},
    [NORMAL_EXIT | DS1] = {"@Exits/DS1/Normal Exit","@Exits/DS1/Swapped Normal Exit"},
    [SECRET_EXIT | DS1] = {"@Exits/DS1/Secret Exit","@Exits/DS1/Swapped Secret Exit"},
    [NORMAL_EXIT | DS2] = {"@Exits/DS2/Normal Exit"},
    [NORMAL_EXIT | DGH] = {"@Exits/DGH/Normal Exit","@Exits/DGH/Swapped Normal Exit"},
    [SECRET_EXIT | DGH] = {"@Exits/DGH/Secret Exit","@Exits/DGH/Swapped Secret Exit"},
    [NORMAL_EXIT | DSH] = {"@Exits/DSH/Normal Exit","@Exits/DSH/Swapped Normal Exit"},
    [SECRET_EXIT | DSH] = {"@Exits/DSH/Secret Exit","@Exits/DSH/Swapped Secret Exit"},
    [NORMAL_EXIT | DPC] = {"@Exits/DPC/Normal Exit"},
    [NORMAL_EXIT | GSP] = {"@Exits/GSP/Normal Exit"},
    [NORMAL_EXIT | VD1] = {"@Exits/VD1/Normal Exit","@Exits/VD1/Swapped Normal Exit"},
    [SECRET_EXIT | VD1] = {"@Exits/VD1/Secret Exit","@Exits/VD1/Swapped Secret Exit"},
    [NORMAL_EXIT | VD2] = {"@Exits/VD2/Normal Exit","@Exits/VD2/Swapped Normal Exit"},
    [SECRET_EXIT | VD2] = {"@Exits/VD2/Secret Exit","@Exits/VD2/Swapped Secret Exit"},
    [NORMAL_EXIT | VD3] = {"@Exits/VD3/Normal Exit"},
    [NORMAL_EXIT | VD4] = {"@Exits/VD4/Normal Exit"},
    [NORMAL_EXIT | VS1] = {"@Exits/VS1/Normal Exit","@Exits/VS1/Swapped Normal Exit"},
    [SECRET_EXIT | VS1] = {"@Exits/VS1/Secret Exit","@Exits/VS1/Swapped Secret Exit"},
    [NORMAL_EXIT | VS2] = {"@Exits/VS2/Normal Exit"},
    [NORMAL_EXIT | VS3] = {"@Exits/VS3/Normal Exit"},
    [NORMAL_EXIT | VDH] = {"@Exits/VDH/Normal Exit"},
    [NORMAL_EXIT | VDF] = {"@Exits/VDF/Normal Exit"},
    [NORMAL_EXIT | VDC] = {"@Exits/VDC/Normal Exit"},
    [NORMAL_EXIT | RSP] = {"@Exits/RSP/Normal Exit"},
    [NORMAL_EXIT | BB1] = {"@Exits/BB1/Normal Exit"},
    [NORMAL_EXIT | BB2] = {"@Exits/BB2/Normal Exit"},
    [NORMAL_EXIT | CBA] = {"@Exits/CBA/Normal Exit","@Exits/CBA/Swapped Normal Exit"},
    [SECRET_EXIT | CBA] = {"@Exits/CBA/Secret Exit","@Exits/CBA/Swapped Secret Exit"},
    [NORMAL_EXIT | COM] = {"@Exits/COM/Normal Exit"},
    [NORMAL_EXIT | SOL] = {"@Exits/SOL/Normal Exit"},
    [NORMAL_EXIT | TWC] = {"@Exits/TWC/Normal Exit"},
    [NORMAL_EXIT | FI1] = {"@Exits/FI1/Normal Exit","@Exits/FI1/Swapped Normal Exit"},
    [SECRET_EXIT | FI1] = {"@Exits/FI1/Secret Exit","@Exits/FI1/Swapped Secret Exit"},
    [NORMAL_EXIT | FI2] = {"@Exits/FI2/Normal Exit","@Exits/FI2/Swapped Normal Exit"},
    [SECRET_EXIT | FI2] = {"@Exits/FI2/Secret Exit","@Exits/FI2/Swapped Secret Exit"},
    [NORMAL_EXIT | FI3] = {"@Exits/FI3/Normal Exit","@Exits/FI3/Swapped Normal Exit"},
    [SECRET_EXIT | FI3] = {"@Exits/FI3/Secret Exit","@Exits/FI3/Swapped Secret Exit"},
    [NORMAL_EXIT | FI4] = {"@Exits/FI4/Normal Exit","@Exits/FI4/Swapped Normal Exit"},
    [SECRET_EXIT | FI4] = {"@Exits/FI4/Secret Exit","@Exits/FI4/Swapped Secret Exit"},
    [NORMAL_EXIT | FGH] = {"@Exits/FGH/Normal Exit","@Exits/FGH/Swapped Normal Exit"},
    [SECRET_EXIT | FGH] = {"@Exits/FGH/Secret Exit","@Exits/FGH/Swapped Secret Exit"},
    [NORMAL_EXIT | FSA] = {"@Exits/FSA/Normal Exit"},
    [NORMAL_EXIT | FIF] = {"@Exits/FIF/Normal Exit"},
    [NORMAL_EXIT | FIC] = {"@Exits/FIC/Normal Exit"},
    [NORMAL_EXIT | BSP] = {"@Exits/BSP/Normal Exit"},
    [NORMAL_EXIT | CI1] = {"@Exits/CI1/Normal Exit"},
    [NORMAL_EXIT | CI2] = {"@Exits/CI2/Normal Exit","@Exits/CI2/Swapped Normal Exit"},
    [SECRET_EXIT | CI2] = {"@Exits/CI2/Secret Exit","@Exits/CI2/Swapped Secret Exit"},
    [NORMAL_EXIT | CI3] = {"@Exits/CI3/Normal Exit","@Exits/CI3/Swapped Normal Exit"},
    [SECRET_EXIT | CI3] = {"@Exits/CI3/Secret Exit","@Exits/CI3/Swapped Secret Exit"},
    [NORMAL_EXIT | CI4] = {"@Exits/CI4/Normal Exit"},
    [NORMAL_EXIT | CI5] = {"@Exits/CI5/Normal Exit"},
    [NORMAL_EXIT | CGH] = {"@Exits/CGH/Normal Exit"},
    [NORMAL_EXIT | CSA] = {"@Exits/CSA/Normal Exit"},
    [NORMAL_EXIT | CIF] = {"@Exits/CIF/Normal Exit"},
    [NORMAL_EXIT | CIC] = {"@Exits/CIC/Normal Exit"},
    [NORMAL_EXIT | SGS] = {"@Exits/SGS/Normal Exit"},
    [NORMAL_EXIT | VB1] = {"@Exits/VB1/Normal Exit"},
    [NORMAL_EXIT | VB2] = {"@Exits/VB2/Normal Exit","@Exits/VB2/Swapped Normal Exit"},
    [SECRET_EXIT | VB2] = {"@Exits/VB2/Secret Exit","@Exits/VB2/Swapped Secret Exit"},
    [NORMAL_EXIT | VB3] = {"@Exits/VB3/Normal Exit"},
    [NORMAL_EXIT | VB4] = {"@Exits/VB4/Normal Exit","@Exits/VB4/Swapped Normal Exit"},
    [SECRET_EXIT | VB4] = {"@Exits/VB4/Secret Exit","@Exits/VB4/Swapped Secret Exit"},
    [NORMAL_EXIT | VBH] = {"@Exits/VBH/Normal Exit","@Exits/VBH/Swapped Normal Exit"},
    [SECRET_EXIT | VBH] = {"@Exits/VBH/Secret Exit","@Exits/VBH/Swapped Secret Exit"},
    [NORMAL_EXIT | VBF] = {"@Exits/VBF/Normal Exit"},
    [NORMAL_EXIT | VBC] = {"@Exits/VBC/Normal Exit"},
    [NORMAL_EXIT | SR1] = {"@Exits/SR1/Normal Exit","@Exits/SR1/Swapped Normal Exit"},
    [SECRET_EXIT | SR1] = {"@Exits/SR1/Secret Exit","@Exits/SR1/Swapped Secret Exit"},
    [NORMAL_EXIT | SR2] = {"@Exits/SR2/Normal Exit","@Exits/SR2/Swapped Normal Exit"},
    [SECRET_EXIT | SR2] = {"@Exits/SR2/Secret Exit","@Exits/SR2/Swapped Secret Exit"},
    [NORMAL_EXIT | SR3] = {"@Exits/SR3/Normal Exit","@Exits/SR3/Swapped Normal Exit"},
    [SECRET_EXIT | SR3] = {"@Exits/SR3/Secret Exit","@Exits/SR3/Swapped Secret Exit"},
    [NORMAL_EXIT | SR4] = {"@Exits/SR4/Normal Exit","@Exits/SR4/Swapped Normal Exit"},
    [SECRET_EXIT | SR4] = {"@Exits/SR4/Secret Exit","@Exits/SR4/Swapped Secret Exit"},
    [NORMAL_EXIT | SR5] = {"@Exits/SR5/Normal Exit","@Exits/SR5/Swapped Normal Exit"},
    [SECRET_EXIT | SR5] = {"@Exits/SR5/Secret Exit","@Exits/SR5/Swapped Secret Exit"},
    [NORMAL_EXIT | SZ1] = {"@Exits/SZ1/Normal Exit"},
    [NORMAL_EXIT | SZ2] = {"@Exits/SZ2/Normal Exit"},
    [NORMAL_EXIT | SZ3] = {"@Exits/SZ3/Normal Exit"},
    [NORMAL_EXIT | SZ4] = {"@Exits/SZ4/Normal Exit"},
    [NORMAL_EXIT | SZ5] = {"@Exits/SZ5/Normal Exit"},
    [NORMAL_EXIT | SZ6] = {"@Exits/SZ6/Normal Exit"},
    [NORMAL_EXIT | SZ7] = {"@Exits/SZ7/Normal Exit"},
    [NORMAL_EXIT | SZ8] = {"@Exits/SZ8/Normal Exit"},
    [DRAGON_COINS | YI1] = {
        "@Dragon Coins/YI1/Dragon Coins",
        "@Dragon Coins/YI1/Dragon Coin #1",
        "@Dragon Coins/YI1/Dragon Coin #2",
        "@Dragon Coins/YI1/Dragon Coin #3",
        "@Dragon Coins/YI1/Dragon Coin #4",
        "@Dragon Coins/YI1/Dragon Coin #5"
    },
    [DRAGON_COINS | YI2] = {
        "@Dragon Coins/YI2/Dragon Coins",
        "@Dragon Coins/YI2/Dragon Coin #1",
        "@Dragon Coins/YI2/Dragon Coin #2",
        "@Dragon Coins/YI2/Dragon Coin #3",
        "@Dragon Coins/YI2/Dragon Coin #4",
        "@Dragon Coins/YI2/Dragon Coin #5"
    },
    [DRAGON_COINS | YI3] = {
        "@Dragon Coins/YI3/Dragon Coins",
        "@Dragon Coins/YI3/Dragon Coin #1",
        "@Dragon Coins/YI3/Dragon Coin #2",
        "@Dragon Coins/YI3/Dragon Coin #3",
        "@Dragon Coins/YI3/Dragon Coin #4",
        "@Dragon Coins/YI3/Dragon Coin #5"
    },
    [DRAGON_COINS | YI4] = {
        "@Dragon Coins/YI4/Dragon Coins",
        "@Dragon Coins/YI4/Dragon Coin #1",
        "@Dragon Coins/YI4/Dragon Coin #2",
        "@Dragon Coins/YI4/Dragon Coin #3",
        "@Dragon Coins/YI4/Dragon Coin #4",
        "@Dragon Coins/YI4/Dragon Coin #5"
    },
    [DRAGON_COINS | DP1] = {
        "@Dragon Coins/DP1/Dragon Coins",
        "@Dragon Coins/DP1/Dragon Coin #1",
        "@Dragon Coins/DP1/Dragon Coin #2",
        "@Dragon Coins/DP1/Dragon Coin #3",
        "@Dragon Coins/DP1/Dragon Coin #4",
        "@Dragon Coins/DP1/Dragon Coin #5"
    },
    [DRAGON_COINS | DP2] = {
        "@Dragon Coins/DP2/Dragon Coins",
        "@Dragon Coins/DP2/Dragon Coin #1",
        "@Dragon Coins/DP2/Dragon Coin #2",
        "@Dragon Coins/DP2/Dragon Coin #3",
        "@Dragon Coins/DP2/Dragon Coin #4",
        "@Dragon Coins/DP2/Dragon Coin #5"
    },
    [DRAGON_COINS | DP3] = {
        "@Dragon Coins/DP3/Dragon Coins",
        "@Dragon Coins/DP3/Dragon Coin #1",
        "@Dragon Coins/DP3/Dragon Coin #2",
        "@Dragon Coins/DP3/Dragon Coin #3",
        "@Dragon Coins/DP3/Dragon Coin #4",
        "@Dragon Coins/DP3/Dragon Coin #5"
    },
    [DRAGON_COINS | DP4] = {
        "@Dragon Coins/DP4/Dragon Coins",
        "@Dragon Coins/DP4/Dragon Coin #1",
        "@Dragon Coins/DP4/Dragon Coin #2",
        "@Dragon Coins/DP4/Dragon Coin #3",
        "@Dragon Coins/DP4/Dragon Coin #4",
        "@Dragon Coins/DP4/Dragon Coin #5"
    },
    [DRAGON_COINS | DS1] = {
        "@Dragon Coins/DS1/Dragon Coins",
        "@Dragon Coins/DS1/Dragon Coin #1",
        "@Dragon Coins/DS1/Dragon Coin #2",
        "@Dragon Coins/DS1/Dragon Coin #3",
        "@Dragon Coins/DS1/Dragon Coin #4",
        "@Dragon Coins/DS1/Dragon Coin #5",
        "@Dragon Coins/DS1/Dragon Coin #6",
        "@Dragon Coins/DS1/Dragon Coin #7"
    },
    [DRAGON_COINS | DS2] = {
        "@Dragon Coins/DS2/Dragon Coins",
        "@Dragon Coins/DS2/Dragon Coin #1",
        "@Dragon Coins/DS2/Dragon Coin #2",
        "@Dragon Coins/DS2/Dragon Coin #3",
        "@Dragon Coins/DS2/Dragon Coin #4",
        "@Dragon Coins/DS2/Dragon Coin #5"
    },
    [DRAGON_COINS | VD1] = {
        "@Dragon Coins/VD1/Dragon Coins",
        "@Dragon Coins/VD1/Dragon Coin #1",
        "@Dragon Coins/VD1/Dragon Coin #2",
        "@Dragon Coins/VD1/Dragon Coin #3",
        "@Dragon Coins/VD1/Dragon Coin #4",
        "@Dragon Coins/VD1/Dragon Coin #5"
    },
    [DRAGON_COINS | VD2] = {
        "@Dragon Coins/VD2/Dragon Coins",
        "@Dragon Coins/VD2/Dragon Coin #1",
        "@Dragon Coins/VD2/Dragon Coin #2",
        "@Dragon Coins/VD2/Dragon Coin #3",
        "@Dragon Coins/VD2/Dragon Coin #4",
        "@Dragon Coins/VD2/Dragon Coin #5"
    },
    [DRAGON_COINS | VD3] = {
        "@Dragon Coins/VD3/Dragon Coins",
        "@Dragon Coins/VD3/Dragon Coin #1",
        "@Dragon Coins/VD3/Dragon Coin #2",
        "@Dragon Coins/VD3/Dragon Coin #3",
        "@Dragon Coins/VD3/Dragon Coin #4",
        "@Dragon Coins/VD3/Dragon Coin #5",
        "@Dragon Coins/VD3/Dragon Coin #6"
    },
    [DRAGON_COINS | VD4] = {
        "@Dragon Coins/VD4/Dragon Coins",
        "@Dragon Coins/VD4/Dragon Coin #1",
        "@Dragon Coins/VD4/Dragon Coin #2",
        "@Dragon Coins/VD4/Dragon Coin #3",
        "@Dragon Coins/VD4/Dragon Coin #4",
        "@Dragon Coins/VD4/Dragon Coin #5"
    },
    [DRAGON_COINS | VS1] = {
        "@Dragon Coins/VS1/Dragon Coins",
        "@Dragon Coins/VS1/Dragon Coin #1",
        "@Dragon Coins/VS1/Dragon Coin #2",
        "@Dragon Coins/VS1/Dragon Coin #3",
        "@Dragon Coins/VS1/Dragon Coin #4",
        "@Dragon Coins/VS1/Dragon Coin #5"
    },
    [DRAGON_COINS | VS2] = {
        "@Dragon Coins/VS2/Dragon Coins",
        "@Dragon Coins/VS2/Dragon Coin #1",
        "@Dragon Coins/VS2/Dragon Coin #2",
        "@Dragon Coins/VS2/Dragon Coin #3",
        "@Dragon Coins/VS2/Dragon Coin #4",
        "@Dragon Coins/VS2/Dragon Coin #5"
    },
    [DRAGON_COINS | VS3] = {
        "@Dragon Coins/VS3/Dragon Coins",
        "@Dragon Coins/VS3/Dragon Coin #1",
        "@Dragon Coins/VS3/Dragon Coin #2",
        "@Dragon Coins/VS3/Dragon Coin #3",
        "@Dragon Coins/VS3/Dragon Coin #4",
        "@Dragon Coins/VS3/Dragon Coin #5"
    },
    [DRAGON_COINS | VDH] = {
        "@Dragon Coins/VDH/Dragon Coins",
        "@Dragon Coins/VDH/Dragon Coin #1",
        "@Dragon Coins/VDH/Dragon Coin #2",
        "@Dragon Coins/VDH/Dragon Coin #3",
        "@Dragon Coins/VDH/Dragon Coin #4",
        "@Dragon Coins/VDH/Dragon Coin #5"
    },
    [DRAGON_COINS | BB1] = {
        "@Dragon Coins/BB1/Dragon Coins",
        "@Dragon Coins/BB1/Dragon Coin #1",
        "@Dragon Coins/BB1/Dragon Coin #2",
        "@Dragon Coins/BB1/Dragon Coin #3",
        "@Dragon Coins/BB1/Dragon Coin #4",
        "@Dragon Coins/BB1/Dragon Coin #5"
    },
    [DRAGON_COINS | BB2] = {
        "@Dragon Coins/BB2/Dragon Coins",
        "@Dragon Coins/BB2/Dragon Coin #1",
        "@Dragon Coins/BB2/Dragon Coin #2",
        "@Dragon Coins/BB2/Dragon Coin #3",
        "@Dragon Coins/BB2/Dragon Coin #4",
        "@Dragon Coins/BB2/Dragon Coin #5"
    },
    [DRAGON_COINS | CBA] = {
        "@Dragon Coins/CBA/Dragon Coins",
        "@Dragon Coins/CBA/Dragon Coin #1",
        "@Dragon Coins/CBA/Dragon Coin #2",
        "@Dragon Coins/CBA/Dragon Coin #3",
        "@Dragon Coins/CBA/Dragon Coin #4",
        "@Dragon Coins/CBA/Dragon Coin #5",
        "@Dragon Coins/CBA/Dragon Coin #6",
        "@Dragon Coins/CBA/Dragon Coin #7",
        "@Dragon Coins/CBA/Dragon Coin #8",
        "@Dragon Coins/CBA/Dragon Coin #9",
        "@Dragon Coins/CBA/Dragon Coin #10"
    },
    [DRAGON_COINS | COM] = {
        "@Dragon Coins/COM/Dragon Coins",
        "@Dragon Coins/COM/Dragon Coin #1",
        "@Dragon Coins/COM/Dragon Coin #2",
        "@Dragon Coins/COM/Dragon Coin #3",
        "@Dragon Coins/COM/Dragon Coin #4",
        "@Dragon Coins/COM/Dragon Coin #5"
    },
    [DRAGON_COINS | SOL] = {
        "@Dragon Coins/SOL/Dragon Coins",
        "@Dragon Coins/SOL/Dragon Coin #1",
        "@Dragon Coins/SOL/Dragon Coin #2",
        "@Dragon Coins/SOL/Dragon Coin #3",
        "@Dragon Coins/SOL/Dragon Coin #4",
        "@Dragon Coins/SOL/Dragon Coin #5"
    },
    [DRAGON_COINS | FI2] = {
        "@Dragon Coins/FI2/Dragon Coins",
        "@Dragon Coins/FI2/Dragon Coin #1",
        "@Dragon Coins/FI2/Dragon Coin #2",
        "@Dragon Coins/FI2/Dragon Coin #3",
        "@Dragon Coins/FI2/Dragon Coin #4",
        "@Dragon Coins/FI2/Dragon Coin #5"
    },
    [DRAGON_COINS | FI3] = {
        "@Dragon Coins/FI3/Dragon Coins",
        "@Dragon Coins/FI3/Dragon Coin #1",
        "@Dragon Coins/FI3/Dragon Coin #2",
        "@Dragon Coins/FI3/Dragon Coin #3",
        "@Dragon Coins/FI3/Dragon Coin #4",
        "@Dragon Coins/FI3/Dragon Coin #5"
    },
    [DRAGON_COINS | FI4] = {
        "@Dragon Coins/FI4/Dragon Coins",
        "@Dragon Coins/FI4/Dragon Coin #1",
        "@Dragon Coins/FI4/Dragon Coin #2",
        "@Dragon Coins/FI4/Dragon Coin #3",
        "@Dragon Coins/FI4/Dragon Coin #4",
        "@Dragon Coins/FI4/Dragon Coin #5"
    },
    [DRAGON_COINS | FGH] = {
        "@Dragon Coins/FGH/Dragon Coins",
        "@Dragon Coins/FGH/Dragon Coin #1",
        "@Dragon Coins/FGH/Dragon Coin #2",
        "@Dragon Coins/FGH/Dragon Coin #3",
        "@Dragon Coins/FGH/Dragon Coin #4",
        "@Dragon Coins/FGH/Dragon Coin #5"
    },
    [DRAGON_COINS | FSA] = {
        "@Dragon Coins/FSA/Dragon Coins",
        "@Dragon Coins/FSA/Dragon Coin #1",
        "@Dragon Coins/FSA/Dragon Coin #2",
        "@Dragon Coins/FSA/Dragon Coin #3",
        "@Dragon Coins/FSA/Dragon Coin #4",
        "@Dragon Coins/FSA/Dragon Coin #5"
    },
    [DRAGON_COINS | FIC] = {
        "@Dragon Coins/FIC/Dragon Coins",
        "@Dragon Coins/FIC/Dragon Coin #1",
        "@Dragon Coins/FIC/Dragon Coin #2",
        "@Dragon Coins/FIC/Dragon Coin #3",
        "@Dragon Coins/FIC/Dragon Coin #4",
        "@Dragon Coins/FIC/Dragon Coin #5"
    },
    [DRAGON_COINS | CI1] = {
        "@Dragon Coins/CI1/Dragon Coins",
        "@Dragon Coins/CI1/Dragon Coin #1",
        "@Dragon Coins/CI1/Dragon Coin #2",
        "@Dragon Coins/CI1/Dragon Coin #3",
        "@Dragon Coins/CI1/Dragon Coin #4",
        "@Dragon Coins/CI1/Dragon Coin #5"
    },
    [DRAGON_COINS | CI2] = {
        "@Dragon Coins/CI2/Dragon Coins",
        "@Dragon Coins/CI2/Dragon Coin #1",
        "@Dragon Coins/CI2/Dragon Coin #2",
        "@Dragon Coins/CI2/Dragon Coin #3",
        "@Dragon Coins/CI2/Dragon Coin #4",
        "@Dragon Coins/CI2/Dragon Coin #5",
        "@Dragon Coins/CI2/Dragon Coin #6",
        "@Dragon Coins/CI2/Dragon Coin #7"
    },
    [DRAGON_COINS | CI3] = {
        "@Dragon Coins/CI3/Dragon Coins",
        "@Dragon Coins/CI3/Dragon Coin #1",
        "@Dragon Coins/CI3/Dragon Coin #2",
        "@Dragon Coins/CI3/Dragon Coin #3",
        "@Dragon Coins/CI3/Dragon Coin #4",
        "@Dragon Coins/CI3/Dragon Coin #5"
    },
    [DRAGON_COINS | CI4] = {
        "@Dragon Coins/CI4/Dragon Coins",
        "@Dragon Coins/CI4/Dragon Coin #1",
        "@Dragon Coins/CI4/Dragon Coin #2",
        "@Dragon Coins/CI4/Dragon Coin #3",
        "@Dragon Coins/CI4/Dragon Coin #4",
        "@Dragon Coins/CI4/Dragon Coin #5"
    },
    [DRAGON_COINS | CI5] = {
        "@Dragon Coins/CI5/Dragon Coins",
        "@Dragon Coins/CI5/Dragon Coin #1",
        "@Dragon Coins/CI5/Dragon Coin #2",
        "@Dragon Coins/CI5/Dragon Coin #3",
        "@Dragon Coins/CI5/Dragon Coin #4",
        "@Dragon Coins/CI5/Dragon Coin #5",
        "@Dragon Coins/CI5/Dragon Coin #6",
        "@Dragon Coins/CI5/Dragon Coin #7"
    },
    [DRAGON_COINS | SGS] = {
        "@Dragon Coins/SGS/Dragon Coins",
        "@Dragon Coins/SGS/Dragon Coin #1",
        "@Dragon Coins/SGS/Dragon Coin #2",
        "@Dragon Coins/SGS/Dragon Coin #3",
        "@Dragon Coins/SGS/Dragon Coin #4",
        "@Dragon Coins/SGS/Dragon Coin #5"
    },
    [DRAGON_COINS | VB1] = {
        "@Dragon Coins/VB1/Dragon Coins",
        "@Dragon Coins/VB1/Dragon Coin #1",
        "@Dragon Coins/VB1/Dragon Coin #2",
        "@Dragon Coins/VB1/Dragon Coin #3",
        "@Dragon Coins/VB1/Dragon Coin #4",
        "@Dragon Coins/VB1/Dragon Coin #5"
    },
    [DRAGON_COINS | VB2] = {
        "@Dragon Coins/VB2/Dragon Coins",
        "@Dragon Coins/VB2/Dragon Coin #1",
        "@Dragon Coins/VB2/Dragon Coin #2",
        "@Dragon Coins/VB2/Dragon Coin #3",
        "@Dragon Coins/VB2/Dragon Coin #4",
        "@Dragon Coins/VB2/Dragon Coin #5",
        "@Dragon Coins/VB2/Dragon Coin #6",
        "@Dragon Coins/VB2/Dragon Coin #7"
    },
    [DRAGON_COINS | VB3] = {
        "@Dragon Coins/VB3/Dragon Coins",
        "@Dragon Coins/VB3/Dragon Coin #1",
        "@Dragon Coins/VB3/Dragon Coin #2",
        "@Dragon Coins/VB3/Dragon Coin #3",
        "@Dragon Coins/VB3/Dragon Coin #4",
        "@Dragon Coins/VB3/Dragon Coin #5"
    },
    [DRAGON_COINS | VBH] = {
        "@Dragon Coins/VBH/Dragon Coins",
        "@Dragon Coins/VBH/Dragon Coin #1",
        "@Dragon Coins/VBH/Dragon Coin #2",
        "@Dragon Coins/VBH/Dragon Coin #3",
        "@Dragon Coins/VBH/Dragon Coin #4",
        "@Dragon Coins/VBH/Dragon Coin #5",
        "@Dragon Coins/VBH/Dragon Coin #6"
    },
    [DRAGON_COINS | VBC] = {
        "@Dragon Coins/VBC/Dragon Coins",
        "@Dragon Coins/VBC/Dragon Coin #1",
        "@Dragon Coins/VBC/Dragon Coin #2",
        "@Dragon Coins/VBC/Dragon Coin #3",
        "@Dragon Coins/VBC/Dragon Coin #4",
        "@Dragon Coins/VBC/Dragon Coin #5"
    },
    [DRAGON_COINS | SR1] = {
        "@Dragon Coins/SR1/Dragon Coins",
        "@Dragon Coins/SR1/Dragon Coin #1",
        "@Dragon Coins/SR1/Dragon Coin #2",
        "@Dragon Coins/SR1/Dragon Coin #3",
        "@Dragon Coins/SR1/Dragon Coin #4",
        "@Dragon Coins/SR1/Dragon Coin #5"
    },
    [DRAGON_COINS | SZ1] = {
        "@Dragon Coins/SZ1/Dragon Coins",
        "@Dragon Coins/SZ1/Dragon Coin #1",
        "@Dragon Coins/SZ1/Dragon Coin #2",
        "@Dragon Coins/SZ1/Dragon Coin #3",
        "@Dragon Coins/SZ1/Dragon Coin #4",
        "@Dragon Coins/SZ1/Dragon Coin #5",
        "@Dragon Coins/SZ1/Dragon Coin #6",
        "@Dragon Coins/SZ1/Dragon Coin #7",
        "@Dragon Coins/SZ1/Dragon Coin #8"
    },
    [DRAGON_COINS | SZ2] = {
        "@Dragon Coins/SZ2/Dragon Coins",
        "@Dragon Coins/SZ2/Dragon Coin #1",
        "@Dragon Coins/SZ2/Dragon Coin #2",
        "@Dragon Coins/SZ2/Dragon Coin #3",
        "@Dragon Coins/SZ2/Dragon Coin #4",
        "@Dragon Coins/SZ2/Dragon Coin #5"
    },
    [DRAGON_COINS | SZ3] = {
        "@Dragon Coins/SZ3/Dragon Coins",
        "@Dragon Coins/SZ3/Dragon Coin #1",
        "@Dragon Coins/SZ3/Dragon Coin #2",
        "@Dragon Coins/SZ3/Dragon Coin #3",
        "@Dragon Coins/SZ3/Dragon Coin #4",
        "@Dragon Coins/SZ3/Dragon Coin #5",
        "@Dragon Coins/SZ3/Dragon Coin #6",
        "@Dragon Coins/SZ3/Dragon Coin #7",
        "@Dragon Coins/SZ3/Dragon Coin #8"
    },
    [DRAGON_COINS | SZ4] = {
        "@Dragon Coins/SZ4/Dragon Coins",
        "@Dragon Coins/SZ4/Dragon Coin #1",
        "@Dragon Coins/SZ4/Dragon Coin #2",
        "@Dragon Coins/SZ4/Dragon Coin #3",
        "@Dragon Coins/SZ4/Dragon Coin #4",
        "@Dragon Coins/SZ4/Dragon Coin #5"
    },
    [DRAGON_COINS | SZ5] = {
        "@Dragon Coins/SZ5/Dragon Coins",
        "@Dragon Coins/SZ5/Dragon Coin #1",
        "@Dragon Coins/SZ5/Dragon Coin #2",
        "@Dragon Coins/SZ5/Dragon Coin #3",
        "@Dragon Coins/SZ5/Dragon Coin #4",
        "@Dragon Coins/SZ5/Dragon Coin #5"
    },
    [DRAGON_COINS | SZ6] = {
        "@Dragon Coins/SZ6/Dragon Coins",
        "@Dragon Coins/SZ6/Dragon Coin #1",
        "@Dragon Coins/SZ6/Dragon Coin #2",
        "@Dragon Coins/SZ6/Dragon Coin #3",
        "@Dragon Coins/SZ6/Dragon Coin #4",
        "@Dragon Coins/SZ6/Dragon Coin #5"
    },
    [DRAGON_COINS | SZ7] = {
        "@Dragon Coins/SZ7/Dragon Coins",
        "@Dragon Coins/SZ7/Dragon Coin #1",
        "@Dragon Coins/SZ7/Dragon Coin #2",
        "@Dragon Coins/SZ7/Dragon Coin #3",
        "@Dragon Coins/SZ7/Dragon Coin #4",
        "@Dragon Coins/SZ7/Dragon Coin #5"
    },
    [DRAGON_COINS | SZ8] = {
        "@Dragon Coins/SZ8/Dragon Coins",
        "@Dragon Coins/SZ8/Dragon Coin #1",
        "@Dragon Coins/SZ8/Dragon Coin #2",
        "@Dragon Coins/SZ8/Dragon Coin #3",
        "@Dragon Coins/SZ8/Dragon Coin #4",
        "@Dragon Coins/SZ8/Dragon Coin #5"
    },
    [MOON | YI1] = {"@Moons/YI1/3-Up Moon"},
    [MOON | DP4] = {"@Moons/DP4/3-Up Moon"},
    [MOON | VD3] = {"@Moons/VD3/3-Up Moon"},
    [MOON | CBA] = {"@Moons/CBA/3-Up Moon"},
    [MOON | FGH] = {"@Moons/FGH/3-Up Moon"},
    [MOON | CI1] = {"@Moons/CI1/3-Up Moon"},
    [MOON | VB1] = {"@Moons/VB1/3-Up Moon"},
    [HIDDEN | YI4] = {"@Hidden 1-Ups/YI4/Hidden 1-Up"},
    [HIDDEN | DP1] = {"@Hidden 1-Ups/DP1/Hidden 1-Up"},
    [HIDDEN | DP4] = {"@Hidden 1-Ups/DP4/Hidden 1-Up"},
    [HIDDEN | DPC] = {"@Hidden 1-Ups/DPC/Hidden 1-Up"},
    [HIDDEN | VD4] = {"@Hidden 1-Ups/VD4/Hidden 1-Up"},
    [HIDDEN | VDH] = {"@Hidden 1-Ups/VDH/Hidden 1-Up"},
    [HIDDEN | VDF] = {"@Hidden 1-Ups/VDF/Hidden 1-Up"},
    [HIDDEN | COM] = {"@Hidden 1-Ups/COM/Hidden 1-Up"},
    [HIDDEN | FI3] = {"@Hidden 1-Ups/FI3/Hidden 1-Up"},
    [HIDDEN | CI2] = {"@Hidden 1-Ups/CI2/Hidden 1-Up"},
    [HIDDEN | CIC] = {"@Hidden 1-Ups/CIC/Hidden 1-Up"},
    [HIDDEN | VB2] = {"@Hidden 1-Ups/VB2/Hidden 1-Up"},
    [HIDDEN | VBC] = {"@Hidden 1-Ups/VBC/Hidden 1-Up"},
    [HIDDEN | SZ1] = {"@Hidden 1-Ups/SZ1/Hidden 1-Up"},
    [PRIZE | YI3] = {"@Bonus 1-Ups/YI3/Bonus 1-Up"},
    [PRIZE | DP3] = {"@Bonus 1-Ups/DP3/Bonus 1-Up"},
    [PRIZE | BB1] = {"@Bonus 1-Ups/BB1/Bonus 1-Up"},
    [PRIZE | CI3] = {"@Bonus 1-Ups/CI3/Bonus 1-Up"},
    [ROOM | YI1 | 0x0105] = {"@Rooms/YI1/Room 0x0105"},
    [ROOM | YI1 | 0x01CB] = {"@Rooms/YI1/Room 0x01CB"},
    [ROOM | YI2 | 0x0106] = {"@Rooms/YI2/Room 0x0106"},
    [ROOM | YI2 | 0x01CA] = {"@Rooms/YI2/Room 0x01CA"},
    [ROOM | YI3 | 0x0103] = {"@Rooms/YI3/Room 0x0103"},
    [ROOM | YI3 | 0x01FD] = {"@Rooms/YI3/Room 0x01FD"},
    [ROOM | YI4 | 0x0102] = {"@Rooms/YI4/Room 0x0102"},
    [ROOM | YI4 | 0x01BE] = {"@Rooms/YI4/Room 0x01BE"},
    [ROOM | YI4 | 0x01FF] = {"@Rooms/YI4/Room 0x01FF"},
    [ROOM | YIC | 0x0101] = {"@Rooms/YIC/Room 0x0101"},
    [ROOM | YIC | 0x01FC] = {"@Rooms/YIC/Room 0x01FC"},
--  [ROOM | YIC | 0x01F6] = {"@Rooms/YIC/Room 0x01F6"},
    [ROOM | YSP | 0x0014] = {"@Rooms/YSP/Room 0x0014"},
    [ROOM | YSP | 0x00CA] = {"@Rooms/YSP/Room 0x00CA"},
    [ROOM | DP1 | 0x0015] = {"@Rooms/DP1/Room 0x0015"},
    [ROOM | DP1 | 0x00FD] = {"@Rooms/DP1/Room 0x00FD"},
    [ROOM | DP1 | 0x00E3] = {"@Rooms/DP1/Room 0x00E3"},
    [ROOM | DP2 | 0x0009] = {"@Rooms/DP2/Room 0x0009"},
    [ROOM | DP2 | 0x00E9] = {"@Rooms/DP2/Room 0x00E9"},
    [ROOM | DP2 | 0x00FF] = {"@Rooms/DP2/Room 0x00FF"},
    [ROOM | DP3 | 0x0005] = {"@Rooms/DP3/Room 0x0005"},
    [ROOM | DP3 | 0x00F4] = {"@Rooms/DP3/Room 0x00F4"},
    [ROOM | DP4 | 0x0006] = {"@Rooms/DP4/Room 0x0006"},
    [ROOM | DP4 | 0x00C3] = {"@Rooms/DP4/Room 0x00C3"},
    [ROOM | DP4 | 0x00D2] = {"@Rooms/DP4/Room 0x00D2"},
    [ROOM | DS1 | 0x000A] = {"@Rooms/DS1/Room 0x000A"},
    [ROOM | DS1 | 0x00C2] = {"@Rooms/DS1/Room 0x00C2"},
    [ROOM | DS2 | 0x010B] = {"@Rooms/DS2/Room 0x010B"},
    [ROOM | DS2 | 0x01C6] = {"@Rooms/DS2/Room 0x01C6"},
    [ROOM | DGH | 0x0004] = {"@Rooms/DGH/Room 0x0004"},
    [ROOM | DGH | 0x00C4] = {"@Rooms/DGH/Room 0x00C4"},
    [ROOM | DGH | 0x00F9] = {"@Rooms/DGH/Room 0x00F9"},
    [ROOM | DGH | 0x00FE] = {"@Rooms/DGH/Room 0x00FE"},
    [ROOM | DGH | 0x00FA] = {"@Rooms/DGH/Room 0x00FA"},
    [ROOM | DGH | 0x00EB] = {"@Rooms/DGH/Room 0x00EB"},
    [ROOM | DSH | 0x0013] = {"@Rooms/DSH/Room 0x0013"},
    [ROOM | DSH | 0x00ED] = {"@Rooms/DSH/Room 0x00ED"},
    [ROOM | DSH | 0x00F1] = {"@Rooms/DSH/Room 0x00F1"},
    [ROOM | DSH | 0x00F0] = {"@Rooms/DSH/Room 0x00F0"},
    [ROOM | DSH | 0x00E4] = {"@Rooms/DSH/Room 0x00E4"},
    [ROOM | DPC | 0x0007] = {"@Rooms/DPC/Room 0x0007"},
    [ROOM | DPC | 0x00E6] = {"@Rooms/DPC/Room 0x00E6"},
    [ROOM | DPC | 0x00E8] = {"@Rooms/DPC/Room 0x00E8"},
    [ROOM | DPC | 0x00E7] = {"@Rooms/DPC/Room 0x00E7"},
--  [ROOM | DPC | 0x00E5] = {"@Rooms/DPC/Room 0x00E5"},
    [ROOM | GSP | 0x0008] = {"@Rooms/GSP/Room 0x0008"},
    [ROOM | GSP | 0x00C9] = {"@Rooms/GSP/Room 0x00C9"},
    [ROOM | VD1 | 0x011A] = {"@Rooms/VD1/Room 0x011A"},
    [ROOM | VD1 | 0x01EF] = {"@Rooms/VD1/Room 0x01EF"},
    [ROOM | VD2 | 0x0118] = {"@Rooms/VD2/Room 0x0118"},
    [ROOM | VD2 | 0x01C3] = {"@Rooms/VD2/Room 0x01C3"},
    [ROOM | VD3 | 0x010A] = {"@Rooms/VD3/Room 0x010A"},
    [ROOM | VD3 | 0x01F7] = {"@Rooms/VD3/Room 0x01F7"},
    [ROOM | VD3 | 0x01C2] = {"@Rooms/VD3/Room 0x01C2"},
    [ROOM | VD4 | 0x0119] = {"@Rooms/VD4/Room 0x0119"},
    [ROOM | VD4 | 0x01F5] = {"@Rooms/VD4/Room 0x01F5"},
    [ROOM | VS1 | 0x0109] = {"@Rooms/VS1/Room 0x0109"},
    [ROOM | VS1 | 0x01F1] = {"@Rooms/VS1/Room 0x01F1"},
    [ROOM | VS1 | 0x01F0] = {"@Rooms/VS1/Room 0x01F0"},
    [ROOM | VS2 | 0x0001] = {"@Rooms/VS2/Room 0x0001"},
    [ROOM | VS2 | 0x00D8] = {"@Rooms/VS2/Room 0x00D8"},
    [ROOM | VS3 | 0x0002] = {"@Rooms/VS3/Room 0x0002"},
    [ROOM | VS3 | 0x00CB] = {"@Rooms/VS3/Room 0x00CB"},
    [ROOM | VDH | 0x0107] = {"@Rooms/VDH/Room 0x0107"},
    [ROOM | VDH | 0x01EA] = {"@Rooms/VDH/Room 0x01EA"},
    [ROOM | VDH | 0x01F9] = {"@Rooms/VDH/Room 0x01F9"},
    [ROOM | VDF | 0x000B] = {"@Rooms/VDF/Room 0x000B"},
    [ROOM | VDF | 0x10E0] = {"@Rooms/VDF/Room 0x10E0"},
--  [ROOM | VDF | 0x00DF] = {"@Rooms/VDF/Room 0x00DF"},
    [ROOM | VDC | 0x011C] = {"@Rooms/VDC/Room 0x011C"},
    [ROOM | VDC | 0x01F4] = {"@Rooms/VDC/Room 0x01F4"},
    [ROOM | VDC | 0x01F3] = {"@Rooms/VDC/Room 0x01F3"},
--  [ROOM | VDC | 0x01F2] = {"@Rooms/VDC/Room 0x01F2"},
    [ROOM | RSP | 0x011B] = {"@Rooms/RSP/Room 0x011B"},
    [ROOM | RSP | 0x01D8] = {"@Rooms/RSP/Room 0x01D8"},
    [ROOM | BB1 | 0x000C] = {"@Rooms/BB1/Room 0x000C"},
    [ROOM | BB1 | 0x00F3] = {"@Rooms/BB1/Room 0x00F3"},
    [ROOM | BB2 | 0x000D] = {"@Rooms/BB2/Room 0x000D"},
    [ROOM | BB2 | 0x00DD] = {"@Rooms/BB2/Room 0x00DD"},
    [ROOM | CBA | 0x000F] = {"@Rooms/CBA/Room 0x000F"},
    [ROOM | CBA | 0x00BF] = {"@Rooms/CBA/Room 0x00BF"},
    [ROOM | CBA | 0x20C8] = {"@Rooms/CBA/Room 0x20C8"},
    [ROOM | COM | 0x0010] = {"@Rooms/COM/Room 0x0010"},
    [ROOM | COM | 0x00C1] = {"@Rooms/COM/Room 0x00C1"},
    [ROOM | SOL | 0x0011] = {"@Rooms/SOL/Room 0x0011"},
    [ROOM | SOL | 0x00C6] = {"@Rooms/SOL/Room 0x00C6"},
    [ROOM | TWC | 0x000E] = {"@Rooms/TWC/Room 0x000E"},
    [ROOM | TWC | 0x00DA] = {"@Rooms/TWC/Room 0x00DA"},
    [ROOM | TWC | 0x00DC] = {"@Rooms/TWC/Room 0x00DC"},
    [ROOM | TWC | 0x00DB] = {"@Rooms/TWC/Room 0x00DB"},
--  [ROOM | TWC | 0x00D9] = {"@Rooms/TWC/Room 0x00D9"},
    [ROOM | FI1 | 0x011E] = {"@Rooms/FI1/Room 0x011E"},
    [ROOM | FI2 | 0x0120] = {"@Rooms/FI2/Room 0x0120"},
    [ROOM | FI3 | 0x0123] = {"@Rooms/FI3/Room 0x0123"},
    [ROOM | FI3 | 0x01BC] = {"@Rooms/FI3/Room 0x01BC"},
    [ROOM | FI3 | 0x01F8] = {"@Rooms/FI3/Room 0x01F8"},
    [ROOM | FI4 | 0x011F] = {"@Rooms/FI4/Room 0x011F"},
    [ROOM | FI4 | 0x01DF] = {"@Rooms/FI4/Room 0x01DF"},
    [ROOM | FI4 | 0x01C1] = {"@Rooms/FI4/Room 0x01C1"},
    [ROOM | FGH | 0x011D] = {"@Rooms/FGH/Room 0x011D"},
    [ROOM | FGH | 0x01FA] = {"@Rooms/FGH/Room 0x01FA"},
    [ROOM | FGH | 0x01E7] = {"@Rooms/FGH/Room 0x01E7"},
    [ROOM | FGH | 0x01E6] = {"@Rooms/FGH/Room 0x01E6"},
    [ROOM | FSA | 0x0122] = {"@Rooms/FSA/Room 0x0122"},
    [ROOM | FIF | 0x001F] = {"@Rooms/FIF/Room 0x001F"},
    [ROOM | FIF | 0x00D6] = {"@Rooms/FIF/Room 0x00D6"},
--  [ROOM | FIF | 0x00D5] = {"@Rooms/FIF/Room 0x00D5"},
    [ROOM | FIC | 0x0020] = {"@Rooms/FIC/Room 0x0020"},
--  [ROOM | FIC | 0x00CC] = {"@Rooms/FIC/Room 0x00CC"},
    [ROOM | BSP | 0x0121] = {"@Rooms/BSP/Room 0x0121"},
    [ROOM | BSP | 0x01D7] = {"@Rooms/BSP/Room 0x01D7"},
    [ROOM | CI1 | 0x0022] = {"@Rooms/CI1/Room 0x0022"},
    [ROOM | CI1 | 0x00BE] = {"@Rooms/CI1/Room 0x00BE"},
    [ROOM | CI2 | 0x0024] = {"@Rooms/CI2/Room 0x0024"},
    [ROOM | CI2 | 0x00CF] = {"@Rooms/CI2/Room 0x00CF"},
    [ROOM | CI2 | 0x00CE] = {"@Rooms/CI2/Room 0x00CE"},
    [ROOM | CI2 | 0x00CD] = {"@Rooms/CI2/Room 0x00CD"},
    [ROOM | CI3 | 0x0023] = {"@Rooms/CI3/Room 0x0023"},
    [ROOM | CI3 | 0x00D7] = {"@Rooms/CI3/Room 0x00D7"},
    [ROOM | CI4 | 0x001D] = {"@Rooms/CI4/Room 0x001D"},
    [ROOM | CI4 | 0x00EA] = {"@Rooms/CI4/Room 0x00EA"},
    [ROOM | CI5 | 0x001C] = {"@Rooms/CI5/Room 0x001C"},
    [ROOM | CI5 | 0x00BD] = {"@Rooms/CI5/Room 0x00BD"},
    [ROOM | CI5 | 0x00C0] = {"@Rooms/CI5/Room 0x00C0"},
    [ROOM | CGH | 0x0021] = {"@Rooms/CGH/Room 0x0021"},
    [ROOM | CGH | 0x00FC] = {"@Rooms/CGH/Room 0x00FC"},
    [ROOM | CGH | 0x00FB] = {"@Rooms/CGH/Room 0x00FB"},
    [ROOM | CSA | 0x0117] = {"@Rooms/CSA/Room 0x0117"},
    [ROOM | CSA | 0x01C0] = {"@Rooms/CSA/Room 0x01C0"},
    [ROOM | CSA | 0x01ED] = {"@Rooms/CSA/Room 0x01ED"},
    [ROOM | CSA | 0x01EC] = {"@Rooms/CSA/Room 0x01EC"},
    [ROOM | CSA | 0x01EE] = {"@Rooms/CSA/Room 0x01EE"},
    [ROOM | CIF | 0x001B] = {"@Rooms/CIF/Room 0x001B"},
    [ROOM | CIF | 0x00EF] = {"@Rooms/CIF/Room 0x00EF"},
--  [ROOM | CIF | 0x00E2] = {"@Rooms/CIF/Room 0x00E2"},
    [ROOM | CIC | 0x001A] = {"@Rooms/CIC/Room 0x001A"},
    [ROOM | CIC | 0x00D4] = {"@Rooms/CIC/Room 0x00D4"},
--  [ROOM | CIC | 0x00D3] = {"@Rooms/CIC/Room 0x00D3"},
    [ROOM | SGS | 0x0018] = {"@Rooms/SGS/Room 0x0018"},
    [ROOM | SGS | 0x00F8] = {"@Rooms/SGS/Room 0x00F8"},
    [ROOM | SGS | 0x00F7] = {"@Rooms/SGS/Room 0x00F7"},
    [ROOM | VB1 | 0x0116] = {"@Rooms/VB1/Room 0x0116"},
    [ROOM | VB1 | 0x01E4] = {"@Rooms/VB1/Room 0x01E4"},
    [ROOM | VB1 | 0x01E5] = {"@Rooms/VB1/Room 0x01E5"},
    [ROOM | VB2 | 0x0115] = {"@Rooms/VB2/Room 0x0115"},
    [ROOM | VB2 | 0x01E3] = {"@Rooms/VB2/Room 0x01E3"},
    [ROOM | VB2 | 0x01E2] = {"@Rooms/VB2/Room 0x01E2"},
    [ROOM | VB3 | 0x0113] = {"@Rooms/VB3/Room 0x0113"},
    [ROOM | VB3 | 0x01BB] = {"@Rooms/VB3/Room 0x01BB"},
    [ROOM | VB4 | 0x010F] = {"@Rooms/VB4/Room 0x010F"},
    [ROOM | VB4 | 0x01BF] = {"@Rooms/VB4/Room 0x01BF"},
    [ROOM | VBH | 0x0114] = {"@Rooms/VBH/Room 0x0114"},
    [ROOM | VBH | 0x01DD] = {"@Rooms/VBH/Room 0x01DD"},
    [ROOM | VBH | 0x11DB] = {"@Rooms/VBH/Room 0x11DB"},
    [ROOM | VBH | 0x01DA] = {"@Rooms/VBH/Room 0x01DA"},
    [ROOM | VBF | 0x0111] = {"@Rooms/VBF/Room 0x0111"},
--  [ROOM | VBF | 0x01DE] = {"@Rooms/VBF/Room 0x01DE"},
    [ROOM | VBC | 0x0110] = {"@Rooms/VBC/Room 0x0110"},
    [ROOM | VBC | 0x01FE] = {"@Rooms/VBC/Room 0x01FE"},
--  [ROOM | VBC | 0x01EB] = {"@Rooms/VBC/Room 0x01EB"},
    [ROOM | SR1 | 0x0134] = {"@Rooms/SR1/Room 0x0134"},
    [ROOM | SR1 | 0x01D6] = {"@Rooms/SR1/Room 0x01D6"},
    [ROOM | SR2 | 0x0130] = {"@Rooms/SR2/Room 0x0130"},
    [ROOM | SR2 | 0x01D5] = {"@Rooms/SR2/Room 0x01D5"},
    [ROOM | SR3 | 0x0132] = {"@Rooms/SR3/Room 0x0132"},
    [ROOM | SR4 | 0x0135] = {"@Rooms/SR4/Room 0x0135"},
    [ROOM | SR5 | 0x0136] = {"@Rooms/SR5/Room 0x0136"},
    [ROOM | SZ1 | 0x012A] = {"@Rooms/SZ1/Room 0x012A"},
    [ROOM | SZ1 | 0x11C4] = {"@Rooms/SZ1/Room 0x11C4"},
    [ROOM | SZ2 | 0x012B] = {"@Rooms/SZ2/Room 0x012B"},
    [ROOM | SZ3 | 0x012C] = {"@Rooms/SZ3/Room 0x012C"},
    [ROOM | SZ3 | 0x01C9] = {"@Rooms/SZ3/Room 0x01C9"},
    [ROOM | SZ3 | 0x21C8] = {"@Rooms/SZ3/Room 0x21C8"},
    [ROOM | SZ4 | 0x012D] = {"@Rooms/SZ4/Room 0x012D"},
    [ROOM | SZ5 | 0x0128] = {"@Rooms/SZ5/Room 0x0128"},
    [ROOM | SZ6 | 0x0127] = {"@Rooms/SZ6/Room 0x0127"},
    [ROOM | SZ6 | 0x01E0] = {"@Rooms/SZ6/Room 0x01E0"},
    [ROOM | SZ6 | 0x01E1] = {"@Rooms/SZ6/Room 0x01E1"},
    [ROOM | SZ7 | 0x0126] = {"@Rooms/SZ7/Room 0x0126"},
    [ROOM | SZ8 | 0x0125] = {"@Rooms/SZ8/Room 0x0125"},
    [CHECKPOINT | YI1] = {"@Midways/YI1/Midway Point"},
    [CHECKPOINT | YI2] = {"@Midways/YI2/Midway Point"},
    [CHECKPOINT | YI3] = {"@Midways/YI3/Midway Point"},
    [CHECKPOINT | YIC] = {"@Midways/YIC/Midway Point"},
    [CHECKPOINT | DP1] = {"@Midways/DP1/Midway Point"},
    [CHECKPOINT | DP3] = {"@Midways/DP3/Midway Point"},
    [CHECKPOINT | DP4] = {"@Midways/DP4/Midway Point"},
    [CHECKPOINT | VD1] = {"@Midways/VD1/Midway Point"},
    [CHECKPOINT | VD2] = {"@Midways/VD2/Midway Point"},
    [CHECKPOINT | VD3] = {"@Midways/VD3/Midway Point"},
    [CHECKPOINT | VD4] = {"@Midways/VD4/Midway Point"},
    [CHECKPOINT | VS2] = {"@Midways/VS2/Midway Point"},
    [CHECKPOINT | VS3] = {"@Midways/VS3/Midway Point"},
    [CHECKPOINT | VDC] = {"@Midways/VDC/Midway Point"},
    [CHECKPOINT | BB2] = {"@Midways/BB2/Midway Point"},
    [CHECKPOINT | CBA] = {"@Midways/CBA/Midway Point"},
    [CHECKPOINT | COM] = {"@Midways/COM/Midway Point"},
    [CHECKPOINT | FI1] = {"@Midways/FI1/Midway Point"},
    [CHECKPOINT | FI3] = {"@Midways/FI3/Midway Point"},
    [CHECKPOINT | FI4] = {"@Midways/FI4/Midway Point"},
    [CHECKPOINT | CI1] = {"@Midways/CI1/Midway Point"},
    [CHECKPOINT | CI3] = {"@Midways/CI3/Midway Point"},
    [CHECKPOINT | CI5] = {"@Midways/CI5/Midway Point"},
    [CHECKPOINT | CSA] = {"@Midways/CSA/Midway Point"},
    [CHECKPOINT | CIF] = {"@Midways/CIF/Midway Point"},
    [CHECKPOINT | CIC] = {"@Midways/CIC/Midway Point"},
    [CHECKPOINT | VB1] = {"@Midways/VB1/Midway Point"},
    [CHECKPOINT | VB2] = {"@Midways/VB2/Midway Point"},
    [CHECKPOINT | VB3] = {"@Midways/VB3/Midway Point"},
    [CHECKPOINT | VB4] = {"@Midways/VB4/Midway Point"},
    [CHECKPOINT | VBC] = {"@Midways/VBC/Midway Point"},
    [BLOCK | VS2 | 0] = {"@Item Blocks/VS2/Yoshi Block #1"},
    [BLOCK | VS2 | 1] = {"@Green Switch Blocks/VS2/Green Switch Palace Block #1"},
    [BLOCK | VS2 | 2] = {"@Item Blocks/VS2/Powerup Block #1"},
    [BLOCK | VS2 | 3] = {"@Item Blocks/VS2/Powerup Block #2"},
    [BLOCK | VS2 | 4] = {"@Coin Blocks/VS2/Multi Coin Block #1"},
    [BLOCK | VS2 | 5] = {"@Item Blocks/VS2/Gray P-Switch Block #1"},
    [BLOCK | VS2 | 6] = {"@Coin Blocks/VS2/Coin Block #1"},
    [BLOCK | VS2 | 7] = {"@Coin Blocks/VS2/Coin Block #2"},
    [BLOCK | VS2 | 8] = {"@Coin Blocks/VS2/Coin Block #3"},
    [BLOCK | VS2 | 9] = {"@Coin Blocks/VS2/Coin Block #4"},
    [BLOCK | VS2 | 10] = {"@Coin Blocks/VS2/Coin Block #5"},
    [BLOCK | VS2 | 11] = {"@Coin Blocks/VS2/Coin Block #6"},
    [BLOCK | VS3 | 12] = {"@Item Blocks/VS3/Powerup Block #1"},
    [BLOCK | VS3 | 13] = {"@Item Blocks/VS3/Powerup Block #2"},
    [BLOCK | DGH | 14] = {"@Item Blocks/DGH/Vine|P-Switch Block #1"},
    [BLOCK | DGH | 15] = {"@Item Blocks/DGH/Directional Coin Block #1"},
    [BLOCK | DGH | 16] = {"@Item Blocks/DGH/1-Up Mushroom Block #1"},
    [BLOCK | DGH | 17] = {"@Item Blocks/DGH/1-Up Mushroom Block #2"},
    [BLOCK | DGH | 18] = {"@Item Blocks/DGH/1-Up Mushroom Block #3"},
    [BLOCK | DGH | 19] = {"@Item Blocks/DGH/1-Up Mushroom Block #4"},
    [BLOCK | DP3 | 20] = {"@Green Switch Blocks/DP3/Green Switch Palace Block #1"},
    [BLOCK | DP3 | 21] = {"@Coin Blocks/DP3/Coin Block #1"},
    [BLOCK | DP3 | 22] = {"@Coin Blocks/DP3/Coin Block #2"},
    [BLOCK | DP3 | 23] = {"@Item Blocks/DP3/Vine Block #1"},
    [BLOCK | DP3 | 24] = {"@Item Blocks/DP3/Powerup Block #1"},
    [BLOCK | DP4 | 25] = {"@Coin Blocks/DP4/Coin Block #1"},
    [BLOCK | DP4 | 26] = {"@Item Blocks/DP4/Powerup Block #1"},
    [BLOCK | DP4 | 27] = {"@Coin Blocks/DP4/Coin Block #2"},
    [BLOCK | DP4 | 28] = {"@Item Blocks/DP4/Yoshi Block #1"},
    [BLOCK | DPC | 29] = {"@Yellow Switch Blocks/DPC/Yellow Switch Palace Block #1"},
    [BLOCK | DPC | 30] = {"@Coin Blocks/DPC/Coin Block #1"},
    [BLOCK | DPC | 31] = {"@Item Blocks/DPC/Powerup Block #1"},
    [BLOCK | DPC | 32] = {"@Coin Blocks/DPC/Coin Block #2"},
    [BLOCK | DPC | 33] = {"@Item Blocks/DPC/Vine Block #1"},
    [BLOCK | DPC | 34] = {"@Invisible Blocks/DPC/Invisible 1-Up Mushroom Block #1"},
    [BLOCK | DPC | 35] = {"@Coin Blocks/DPC/Coin Block #3"},
    [BLOCK | DPC | 36] = {"@Coin Blocks/DPC/Coin Block #4"},
    [BLOCK | DPC | 37] = {"@Coin Blocks/DPC/Coin Block #5"},
    [BLOCK | DPC | 38] = {"@Green Switch Blocks/DPC/Green Switch Palace Block #1"},
    [BLOCK | DP2 | 39] = {"@Coin Blocks/DP2/Coin Block #1"},
    [BLOCK | DP2 | 40] = {"@Coin Blocks/DP2/Multi Coin Block #1"},
    [BLOCK | DP2 | 41] = {"@Coin Blocks/DP2/Coin Block #2"},
    [BLOCK | DP2 | 42] = {"@Yellow Switch Blocks/DP2/Yellow Switch Palace Block #1"},
    [BLOCK | DP2 | 43] = {"@Item Blocks/DP2/Powerup Block #1"},
    [BLOCK | DP2 | 44] = {"@Coin Blocks/DP2/Multi Coin Block #2"},
    [BLOCK | DP2 | 45] = {"@Flying Blocks/DP2/Flying Question Block #1"},
    [BLOCK | DP2 | 46] = {"@Green Switch Blocks/DP2/Green Switch Palace Block #1"},
    [BLOCK | DP2 | 47] = {"@Yellow Switch Blocks/DP2/Yellow Switch Palace Block #2"},
    [BLOCK | DP2 | 48] = {"@Item Blocks/DP2/Vine Block #1"},
    [BLOCK | DS1 | 49] = {"@Coin Blocks/DS1/Coin Block #1"},
    [BLOCK | DS1 | 50] = {"@Coin Blocks/DS1/Coin Block #2"},
    [BLOCK | DS1 | 51] = {"@Item Blocks/DS1/Powerup Block #1"},
    [BLOCK | DS1 | 52] = {"@Coin Blocks/DS1/Coin Block #3"},
    [BLOCK | DS1 | 53] = {"@Item Blocks/DS1/Powerup Block #2"},
    [BLOCK | DS1 | 54] = {"@Item Blocks/DS1/Powerup Block #3"},
    [BLOCK | DS1 | 55] = {"@Item Blocks/DS1/1-Up Mushroom Block #1"},
    [BLOCK | DS1 | 56] = {"@Item Blocks/DS1/Powerup Block #4"},
    [BLOCK | DS1 | 57] = {"@Item Blocks/DS1/Powerup Block #5"},
    [BLOCK | DS1 | 58] = {"@Item Blocks/DS1/Key Block #1"},
    [BLOCK | VDF | 59] = {"@Item Blocks/VDF/Powerup Block #1"},
    [BLOCK | VDF | 60] = {"@Item Blocks/VDF/Powerup Block #2"},
    [BLOCK | VDF | 61] = {"@Yellow Switch Blocks/VDF/Yellow Switch Palace Block #1"},
    [BLOCK | BB1 | 62] = {"@Item Blocks/BB1/Powerup Block #1"},
    [BLOCK | BB1 | 63] = {"@Coin Blocks/BB1/Multi Coin Block #1"},
    [BLOCK | BB1 | 64] = {"@Coin Blocks/BB1/Multi Coin Block #2"},
    [BLOCK | BB1 | 65] = {"@Coin Blocks/BB1/Multi Coin Block #3"},
    [BLOCK | BB1 | 66] = {"@Item Blocks/BB1/1-Up Mushroom Block #1"},
    [BLOCK | BB2 | 67] = {"@Item Blocks/BB2/Powerup Block #1"},
    [BLOCK | BB2 | 68] = {"@Green Switch Blocks/BB2/Green Switch Palace Block #1"},
    [BLOCK | BB2 | 69] = {"@Item Blocks/BB2/Yoshi Block #1"},
    [BLOCK | TWC | 70] = {"@Item Blocks/TWC/Powerup Block #1"},
    [BLOCK | CBA | 71] = {"@Item Blocks/CBA/Powerup Block #1"},
    [BLOCK | CBA | 72] = {"@Item Blocks/CBA/Powerup Block #2"},
    [BLOCK | CBA | 73] = {"@Item Blocks/CBA/Wings Block #1"},
    [BLOCK | CBA | 74] = {"@Item Blocks/CBA/Powerup Block #3"},
    [BLOCK | COM | 75] = {"@Coin Blocks/COM/Coin Block #1"},
    [BLOCK | COM | 76] = {"@Coin Blocks/COM/Coin Block #2"},
    [BLOCK | COM | 77] = {"@Coin Blocks/COM/Coin Block #3"},
    [BLOCK | COM | 78] = {"@Coin Blocks/COM/Coin Block #4"},
    [BLOCK | COM | 79] = {"@Coin Blocks/COM/Coin Block #5"},
    [BLOCK | COM | 80] = {"@Coin Blocks/COM/Coin Block #6"},
    [BLOCK | COM | 81] = {"@Coin Blocks/COM/Coin Block #7"},
    [BLOCK | COM | 82] = {"@Coin Blocks/COM/Coin Block #8"},
    [BLOCK | COM | 83] = {"@Coin Blocks/COM/Coin Block #9"},
    [BLOCK | COM | 84] = {"@Item Blocks/COM/Powerup Block #1"},
    [BLOCK | COM | 85] = {"@Item Blocks/COM/1-Up Mushroom Block #1"},
    [BLOCK | COM | 86] = {"@Item Blocks/COM/Vine Block #1"},
    [BLOCK | COM | 87] = {"@Item Blocks/COM/Yoshi Block #1"},
    [BLOCK | COM | 88] = {"@Coin Blocks/COM/Coin Block #10"},
    [BLOCK | COM | 89] = {"@Coin Blocks/COM/Coin Block #11"},
    [BLOCK | COM | 90] = {"@Item Blocks/COM/Powerup Block #2"},
    [BLOCK | COM | 91] = {"@Coin Blocks/COM/Coin Block #12"},
    [BLOCK | COM | 92] = {"@Coin Blocks/COM/Coin Block #13"},
    [BLOCK | COM | 93] = {"@Coin Blocks/COM/Coin Block #14"},
    [BLOCK | COM | 94] = {"@Coin Blocks/COM/Coin Block #15"},
    [BLOCK | COM | 95] = {"@Coin Blocks/COM/Coin Block #16"},
    [BLOCK | COM | 96] = {"@Coin Blocks/COM/Coin Block #17"},
    [BLOCK | COM | 97] = {"@Coin Blocks/COM/Coin Block #18"},
    [BLOCK | COM | 98] = {"@Coin Blocks/COM/Coin Block #19"},
    [BLOCK | COM | 99] = {"@Coin Blocks/COM/Coin Block #20"},
    [BLOCK | COM | 100] = {"@Coin Blocks/COM/Coin Block #21"},
    [BLOCK | COM | 101] = {"@Coin Blocks/COM/Coin Block #22"},
    [BLOCK | COM | 102] = {"@Coin Blocks/COM/Coin Block #23"},
    [BLOCK | COM | 103] = {"@Coin Blocks/COM/Coin Block #24"},
    [BLOCK | COM | 104] = {"@Coin Blocks/COM/Coin Block #25"},
    [BLOCK | COM | 105] = {"@Coin Blocks/COM/Coin Block #26"},
    [BLOCK | COM | 106] = {"@Coin Blocks/COM/Coin Block #27"},
    [BLOCK | COM | 107] = {"@Coin Blocks/COM/Coin Block #28"},
    [BLOCK | COM | 108] = {"@Coin Blocks/COM/Coin Block #29"},
    [BLOCK | COM | 109] = {"@Coin Blocks/COM/Coin Block #30"},
    [BLOCK | SOL | 110] = {"@Item Blocks/SOL/Powerup Block #1"},
    [BLOCK | DSH | 111] = {"@Item Blocks/DSH/Powerup Block #1"},
    [BLOCK | DSH | 112] = {"@Coin Blocks/DSH/Multi Coin Block #1"},
    [BLOCK | DSH | 113] = {"@Item Blocks/DSH/1-Up Mushroom Block #1"},
    [BLOCK | DSH | 114] = {"@Item Blocks/DSH/Vine Block #1"},
    [BLOCK | DSH | 115] = {"@Item Blocks/DSH/Directional Coin Block #1"},
    [BLOCK | DP1 | 116] = {"@Coin Blocks/DP1/Coin Block #1"},
    [BLOCK | DP1 | 117] = {"@Coin Blocks/DP1/Coin Block #2"},
    [BLOCK | DP1 | 118] = {"@Item Blocks/DP1/Yoshi Block #1"},
    [BLOCK | DP1 | 119] = {"@Item Blocks/DP1/Vine Block #1"},
    [BLOCK | DP1 | 120] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #1"},
    [BLOCK | DP1 | 121] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #2"},
    [BLOCK | DP1 | 122] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #3"},
    [BLOCK | DP1 | 123] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #4"},
    [BLOCK | DP1 | 124] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #5"},
    [BLOCK | DP1 | 125] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #6"},
    [BLOCK | DP1 | 126] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #7"},
    [BLOCK | DP1 | 127] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #8"},
    [BLOCK | DP1 | 128] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #9"},
    [BLOCK | DP1 | 129] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #10"},
    [BLOCK | DP1 | 130] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #11"},
    [BLOCK | DP1 | 131] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #12"},
    [BLOCK | DP1 | 132] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #13"},
    [BLOCK | DP1 | 133] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #14"},
    [BLOCK | DP1 | 134] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #15"},
    [BLOCK | DP1 | 135] = {"@Green Switch Blocks/DP1/Green Switch Palace Block #16"},
    [BLOCK | DP1 | 136] = {"@Yellow Switch Blocks/DP1/Yellow Switch Palace Block #1"},
    [BLOCK | DP1 | 137] = {"@Yellow Switch Blocks/DP1/Yellow Switch Palace Block #2"},
    [BLOCK | DP1 | 138] = {"@Yellow Switch Blocks/DP1/Yellow Switch Palace Block #3"},
    [BLOCK | SGS | 139] = {"@Item Blocks/SGS/Powerup Block #1"},
    [BLOCK | SGS | 140] = {"@Item Blocks/SGS/Star Block #1"},
    [BLOCK | CIC | 141] = {"@Yellow Switch Blocks/CIC/Yellow Switch Palace Block #1"},
    [BLOCK | CIC | 142] = {"@Yellow Switch Blocks/CIC/Yellow Switch Palace Block #2"},
    [BLOCK | CIC | 143] = {"@Green Switch Blocks/CIC/Green Switch Palace Block #1"},
    [BLOCK | CIF | 144] = {"@Item Blocks/CIF/Powerup Block #1"},
    [BLOCK | CIF | 145] = {"@Item Blocks/CIF/Powerup Block #2"},
    [BLOCK | CIF | 146] = {"@Coin Blocks/CIF/Coin Block #1"},
    [BLOCK | CIF | 147] = {"@Coin Blocks/CIF/Coin Block #2"},
    [BLOCK | CIF | 148] = {"@Green Switch Blocks/CIF/Green Switch Palace Block #1"},
    [BLOCK | CI5 | 149] = {"@Item Blocks/CI5/Yoshi Block #1"},
    [BLOCK | CI5 | 150] = {"@Item Blocks/CI5/Powerup Block #1"},
    [BLOCK | CI5 | 151] = {"@Item Blocks/CI5/1-Up Mushroom Block #1"},
    [BLOCK | CI5 | 152] = {"@Yellow Switch Blocks/CI5/Yellow Switch Palace Block #1"},
    [BLOCK | CI4 | 153] = {"@Yellow Switch Blocks/CI4/Yellow Switch Palace Block #1"},
    [BLOCK | CI4 | 154] = {"@Item Blocks/CI4/Blue P-Switch Block #1"},
    [BLOCK | CI4 | 155] = {"@Item Blocks/CI4/Powerup Block #1"},
    [BLOCK | FIF | 156] = {"@Yellow Switch Blocks/FIF/Yellow Switch Palace Block #1"},
    [BLOCK | FIF | 157] = {"@Item Blocks/FIF/Powerup Block #1"},
    [BLOCK | FIF | 158] = {"@Item Blocks/FIF/1-Up Mushroom Block #1"},
    [BLOCK | FIF | 159] = {"@Item Blocks/FIF/1-Up Mushroom Block #2"},
    [BLOCK | FIF | 160] = {"@Item Blocks/FIF/1-Up Mushroom Block #3"},
    [BLOCK | FIF | 161] = {"@Item Blocks/FIF/1-Up Mushroom Block #4"},
    [BLOCK | FIF | 162] = {"@Item Blocks/FIF/1-Up Mushroom Block #5"},
    [BLOCK | FIF | 163] = {"@Item Blocks/FIF/1-Up Mushroom Block #6"},
    [BLOCK | FIF | 164] = {"@Item Blocks/FIF/1-Up Mushroom Block #7"},
    [BLOCK | FIF | 165] = {"@Item Blocks/FIF/1-Up Mushroom Block #8"},
    [BLOCK | FIF | 166] = {"@Item Blocks/FIF/1-Up Mushroom Block #9"},
    [BLOCK | FIC | 167] = {"@Green Switch Blocks/FIC/Green Switch Palace Block #1"},
    [BLOCK | CGH | 168] = {"@Item Blocks/CGH/Powerup Block #1"},
    [BLOCK | CGH | 169] = {"@Item Blocks/CGH/Powerup Block #2"},
    [BLOCK | CGH | 170] = {"@Item Blocks/CGH/1-Up Mushroom Block #1"},
    [BLOCK | CI1 | 171] = {"@Flying Blocks/CI1/Flying Question Block #1"},
    [BLOCK | CI1 | 172] = {"@Flying Blocks/CI1/Flying Question Block #2"},
    [BLOCK | CI1 | 173] = {"@Item Blocks/CI1/Yoshi Block #1"},
    [BLOCK | CI1 | 174] = {"@Item Blocks/CI1/Green|Yellow Switch Palace Block #1"},
    [BLOCK | CI1 | 175] = {"@Item Blocks/CI1/1-Up Mushroom Block #1"},
    [BLOCK | CI3 | 176] = {"@Item Blocks/CI3/Powerup Block #1"},
    [BLOCK | CI3 | 177] = {"@Item Blocks/CI3/Powerup Block #2"},
    [BLOCK | CI3 | 178] = {"@Item Blocks/CI3/Powerup Block #3"},
    [BLOCK | CI3 | 179] = {"@Green Switch Blocks/CI3/Green Switch Palace Block #1"},
    [BLOCK | CI3 | 180] = {"@Item Blocks/CI3/Vine Block #1"},
    [BLOCK | CI3 | 181] = {"@Item Blocks/CI3/1-Up Mushroom Block #1"},
    [BLOCK | CI3 | 182] = {"@Item Blocks/CI3/1-Up Mushroom Block #2"},
    [BLOCK | CI3 | 183] = {"@Item Blocks/CI3/1-Up Mushroom Block #3"},
    [BLOCK | CI2 | 184] = {"@Coin Blocks/CI2/Multi Coin Block #1"},
    [BLOCK | CI2 | 185] = {"@Invisible Blocks/CI2/Invisible Coin Block #1"},
    [BLOCK | CI2 | 186] = {"@Item Blocks/CI2/Yoshi Block #1"},
    [BLOCK | CI2 | 187] = {"@Coin Blocks/CI2/Coin Block #1"},
    [BLOCK | CI2 | 188] = {"@Coin Blocks/CI2/Coin Block #2"},
    [BLOCK | CI2 | 189] = {"@Coin Blocks/CI2/Multi Coin Block #2"},
    [BLOCK | CI2 | 190] = {"@Item Blocks/CI2/Powerup Block #1"},
    [BLOCK | CI2 | 191] = {"@Item Blocks/CI2/Blue P-Switch Block #1"},
    [BLOCK | CI2 | 192] = {"@Yellow Switch Blocks/CI2/Yellow Switch Palace Block #1"},
    [BLOCK | CI2 | 193] = {"@Yellow Switch Blocks/CI2/Yellow Switch Palace Block #2"},
    [BLOCK | CI2 | 194] = {"@Green Switch Blocks/CI2/Green Switch Palace Block #1"},
    [BLOCK | CI2 | 195] = {"@Green Switch Blocks/CI2/Green Switch Palace Block #2"},
    [BLOCK | CI2 | 196] = {"@Green Switch Blocks/CI2/Green Switch Palace Block #3"},
    [BLOCK | CI2 | 197] = {"@Green Switch Blocks/CI2/Green Switch Palace Block #4"},
    [BLOCK | CI2 | 198] = {"@Green Switch Blocks/CI2/Green Switch Palace Block #5"},
    [BLOCK | CI2 | 199] = {"@Green Switch Blocks/CI2/Green Switch Palace Block #6"},
    [BLOCK | YIC | 200] = {"@Coin Blocks/YIC/Coin Block #1"},
    [BLOCK | YIC | 201] = {"@Coin Blocks/YIC/Coin Block #2"},
    [BLOCK | YIC | 202] = {"@Item Blocks/YIC/Powerup Block #1"},
    [BLOCK | YIC | 203] = {"@Coin Blocks/YIC/Coin Block #3"},
    [BLOCK | YIC | 204] = {"@Coin Blocks/YIC/Coin Block #4"},
    [BLOCK | YIC | 205] = {"@Flying Blocks/YIC/Flying Question Block #1"},
    [BLOCK | YI4 | 206] = {"@Yellow Switch Blocks/YI4/Yellow Switch Palace Block #1"},
    [BLOCK | YI4 | 207] = {"@Item Blocks/YI4/Powerup Block #1"},
    [BLOCK | YI4 | 208] = {"@Coin Blocks/YI4/Multi Coin Block #1"},
    [BLOCK | YI4 | 209] = {"@Item Blocks/YI4/Star Block #1"},
    [BLOCK | YI3 | 210] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #1"},
    [BLOCK | YI3 | 211] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #2"},
    [BLOCK | YI3 | 212] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #3"},
    [BLOCK | YI3 | 213] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #4"},
    [BLOCK | YI3 | 214] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #5"},
    [BLOCK | YI3 | 215] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #6"},
    [BLOCK | YI3 | 216] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #7"},
    [BLOCK | YI3 | 217] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #8"},
    [BLOCK | YI3 | 218] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #9"},
    [BLOCK | YI3 | 219] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #10"},
    [BLOCK | YI3 | 220] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #11"},
    [BLOCK | YI3 | 221] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #12"},
    [BLOCK | YI3 | 222] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #13"},
    [BLOCK | YI3 | 223] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #14"},
    [BLOCK | YI3 | 224] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #15"},
    [BLOCK | YI3 | 225] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #16"},
    [BLOCK | YI3 | 226] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #17"},
    [BLOCK | YI3 | 227] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #18"},
    [BLOCK | YI3 | 228] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #19"},
    [BLOCK | YI3 | 229] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #20"},
    [BLOCK | YI3 | 230] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #21"},
    [BLOCK | YI3 | 231] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #22"},
    [BLOCK | YI3 | 232] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #23"},
    [BLOCK | YI3 | 233] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #24"},
    [BLOCK | YI3 | 234] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #25"},
    [BLOCK | YI3 | 235] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #26"},
    [BLOCK | YI3 | 236] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #27"},
    [BLOCK | YI3 | 237] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #28"},
    [BLOCK | YI3 | 238] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #29"},
    [BLOCK | YI3 | 239] = {"@Coin Blocks/YI3/Coin Block #1"},
    [BLOCK | YI3 | 240] = {"@Item Blocks/YI3/Yoshi Block #1"},
    [BLOCK | YI3 | 241] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #30"},
    [BLOCK | YI3 | 242] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #31"},
    [BLOCK | YI3 | 243] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #32"},
    [BLOCK | YI3 | 244] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #33"},
    [BLOCK | YI3 | 245] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #34"},
    [BLOCK | YI3 | 246] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #35"},
    [BLOCK | YI3 | 247] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #36"},
    [BLOCK | YI3 | 248] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #37"},
    [BLOCK | YI3 | 249] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #38"},
    [BLOCK | YI3 | 250] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #39"},
    [BLOCK | YI3 | 251] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #40"},
    [BLOCK | YI3 | 252] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #41"},
    [BLOCK | YI3 | 253] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #42"},
    [BLOCK | YI3 | 254] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #43"},
    [BLOCK | YI3 | 255] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #44"},
    [BLOCK | YI3 | 256] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #45"},
    [BLOCK | YI3 | 257] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #46"},
    [BLOCK | YI3 | 258] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #47"},
    [BLOCK | YI3 | 259] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #48"},
    [BLOCK | YI3 | 260] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #49"},
    [BLOCK | YI3 | 261] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #50"},
    [BLOCK | YI3 | 262] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #51"},
    [BLOCK | YI3 | 263] = {"@Coin Blocks/YI3/Coin Block #2"},
    [BLOCK | YI3 | 264] = {"@Item Blocks/YI3/Powerup Block #1"},
    [BLOCK | YI3 | 265] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #52"},
    [BLOCK | YI3 | 266] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #53"},
    [BLOCK | YI3 | 267] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #54"},
    [BLOCK | YI3 | 268] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #55"},
    [BLOCK | YI3 | 269] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #56"},
    [BLOCK | YI3 | 270] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #57"},
    [BLOCK | YI3 | 271] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #58"},
    [BLOCK | YI3 | 272] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #59"},
    [BLOCK | YI3 | 273] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #60"},
    [BLOCK | YI3 | 274] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #61"},
    [BLOCK | YI3 | 275] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #62"},
    [BLOCK | YI3 | 276] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #63"},
    [BLOCK | YI3 | 277] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #64"},
    [BLOCK | YI3 | 278] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #65"},
    [BLOCK | YI3 | 279] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #66"},
    [BLOCK | YI3 | 280] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #67"},
    [BLOCK | YI3 | 281] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #68"},
    [BLOCK | YI3 | 282] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #69"},
    [BLOCK | YI3 | 283] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #70"},
    [BLOCK | YI3 | 284] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #71"},
    [BLOCK | YI3 | 285] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #72"},
    [BLOCK | YI3 | 286] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #73"},
    [BLOCK | YI3 | 287] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #74"},
    [BLOCK | YI3 | 288] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #75"},
    [BLOCK | YI3 | 289] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #76"},
    [BLOCK | YI3 | 290] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #77"},
    [BLOCK | YI3 | 291] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #78"},
    [BLOCK | YI3 | 292] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #79"},
    [BLOCK | YI3 | 293] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #80"},
    [BLOCK | YI3 | 294] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #81"},
    [BLOCK | YI3 | 295] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #82"},
    [BLOCK | YI3 | 296] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #83"},
    [BLOCK | YI3 | 297] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #84"},
    [BLOCK | YI3 | 298] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #85"},
    [BLOCK | YI3 | 299] = {"@Yellow Switch Blocks/YI3/Yellow Switch Palace Block #86"},
    [BLOCK | YI1 | 300] = {"@Flying Blocks/YI1/Flying Question Block #1"},
    [BLOCK | YI1 | 301] = {"@Yellow Switch Blocks/YI1/Yellow Switch Palace Block #1"},
    [BLOCK | YI1 | 302] = {"@Item Blocks/YI1/1-Up Mushroom Block #1"},
    [BLOCK | YI1 | 303] = {"@Item Blocks/YI1/Powerup Block #1"},
    [BLOCK | YI2 | 304] = {"@Flying Blocks/YI2/Flying Question Block #1"},
    [BLOCK | YI2 | 305] = {"@Flying Blocks/YI2/Flying Question Block #2"},
    [BLOCK | YI2 | 306] = {"@Flying Blocks/YI2/Flying Question Block #3"},
    [BLOCK | YI2 | 307] = {"@Flying Blocks/YI2/Flying Question Block #4"},
    [BLOCK | YI2 | 308] = {"@Flying Blocks/YI2/Flying Question Block #5"},
    [BLOCK | YI2 | 309] = {"@Flying Blocks/YI2/Flying Question Block #6"},
    [BLOCK | YI2 | 310] = {"@Coin Blocks/YI2/Coin Block #1"},
    [BLOCK | YI2 | 311] = {"@Yellow Switch Blocks/YI2/Yellow Switch Palace Block #1"},
    [BLOCK | YI2 | 312] = {"@Coin Blocks/YI2/Coin Block #2"},
    [BLOCK | YI2 | 313] = {"@Coin Blocks/YI2/Coin Block #3"},
    [BLOCK | YI2 | 314] = {"@Item Blocks/YI2/Yoshi Block #1"},
    [BLOCK | YI2 | 315] = {"@Coin Blocks/YI2/Coin Block #4"},
    [BLOCK | YI2 | 316] = {"@Item Blocks/YI2/Yoshi Block #2"},
    [BLOCK | YI2 | 317] = {"@Coin Blocks/YI2/Coin Block #5"},
    [BLOCK | YI2 | 318] = {"@Item Blocks/YI2/Vine Block #1"},
    [BLOCK | YI2 | 319] = {"@Yellow Switch Blocks/YI2/Yellow Switch Palace Block #2"},
    [BLOCK | VDH | 320] = {"@Item Blocks/VDH/Powerup Block #1"},
    [BLOCK | VDH | 321] = {"@Item Blocks/VDH/Vine Block #1"},
    [BLOCK | VDH | 322] = {"@Item Blocks/VDH/Powerup Block #2"},
    [BLOCK | VDH | 323] = {"@Coin Blocks/VDH/Multi Coin Block #1"},
    [BLOCK | VDH | 324] = {"@Item Blocks/VDH/Blue P-Switch Block #1"},
    [BLOCK | VS1 | 325] = {"@Coin Blocks/VS1/Coin Block #1"},
    [BLOCK | VS1 | 326] = {"@Item Blocks/VS1/Powerup Block #1"},
    [BLOCK | VS1 | 327] = {"@Coin Blocks/VS1/Multi Coin Block #1"},
    [BLOCK | VS1 | 328] = {"@Item Blocks/VS1/Vine Block #1"},
    [BLOCK | VS1 | 329] = {"@Item Blocks/VS1/Vine Block #2"},
    [BLOCK | VS1 | 330] = {"@Coin Blocks/VS1/Coin Block #2"},
    [BLOCK | VS1 | 331] = {"@Coin Blocks/VS1/Coin Block #3"},
    [BLOCK | VS1 | 332] = {"@Item Blocks/VS1/Powerup Block #2"},
    [BLOCK | VD3 | 333] = {"@Coin Blocks/VD3/Coin Block #1"},
    [BLOCK | VD3 | 334] = {"@Flying Blocks/VD3/Flying Question Block #1"},
    [BLOCK | VD3 | 335] = {"@Flying Blocks/VD3/Flying Question Block #2"},
    [BLOCK | VD3 | 336] = {"@Item Blocks/VD3/Powerup Block #1"},
    [BLOCK | VD3 | 337] = {"@Flying Blocks/VD3/Flying Question Block #3"},
    [BLOCK | VD3 | 338] = {"@Invisible Blocks/VD3/Invisible Coin Block #1"},
    [BLOCK | VD3 | 339] = {"@Item Blocks/VD3/Powerup Block #2"},
    [BLOCK | VD3 | 340] = {"@Coin Blocks/VD3/Multi Coin Block #1"},
    [BLOCK | VD3 | 341] = {"@Item Blocks/VD3/Powerup Block #3"},
    [BLOCK | VD3 | 342] = {"@Item Blocks/VD3/Yoshi Block #1"},
    [BLOCK | VD3 | 343] = {"@Item Blocks/VD3/Powerup Block #4"},
    [BLOCK | VD3 | 344] = {"@P-Switch Blocks/VD3/P-Switch Coin Block #1"},
    [BLOCK | VD3 | 345] = {"@P-Switch Blocks/VD3/P-Switch Coin Block #2"},
    [BLOCK | VD3 | 346] = {"@P-Switch Blocks/VD3/P-Switch Coin Block #3"},
    [BLOCK | VD3 | 347] = {"@P-Switch Blocks/VD3/P-Switch Coin Block #4"},
    [BLOCK | VD3 | 348] = {"@P-Switch Blocks/VD3/P-Switch Coin Block #5"},
    [BLOCK | VD3 | 349] = {"@P-Switch Blocks/VD3/P-Switch Coin Block #6"},
    [BLOCK | DS2 | 350] = {"@Item Blocks/DS2/Directional Coin Block #1"},
    [BLOCK | DS2 | 351] = {"@Item Blocks/DS2/Vine Block #1"},
    [BLOCK | DS2 | 352] = {"@Item Blocks/DS2/Star Block #1"},
    [BLOCK | DS2 | 353] = {"@Item Blocks/DS2/Powerup Block #1"},
    [BLOCK | DS2 | 354] = {"@Item Blocks/DS2/Star Block #2"},
    [BLOCK | VB4 | 355] = {"@Yellow Switch Blocks/VB4/Yellow Switch Palace Block #1"},
    [BLOCK | VB4 | 356] = {"@Item Blocks/VB4/Powerup Block #1"},
    [BLOCK | VB4 | 357] = {"@Item Blocks/VB4/Vine Block #1"},
    [BLOCK | VB4 | 358] = {"@Item Blocks/VB4/Yoshi Block #1"},
    [BLOCK | VB4 | 359] = {"@Item Blocks/VB4/1-Up Mushroom Block #1"},
    [BLOCK | VB4 | 360] = {"@Item Blocks/VB4/Powerup Block #2"},
    [BLOCK | VBC | 361] = {"@Yellow Switch Blocks/VBC/Yellow Switch Palace Block #1"},
    [BLOCK | VBC | 362] = {"@Yellow Switch Blocks/VBC/Yellow Switch Palace Block #2"},
    [BLOCK | VBC | 363] = {"@Green Switch Blocks/VBC/Green Switch Palace Block #1"},
    [BLOCK | VBF | 364] = {"@Green Switch Blocks/VBF/Green Switch Palace Block #1"},
    [BLOCK | VBF | 365] = {"@Yellow Switch Blocks/VBF/Yellow Switch Palace Block #1"},
    [BLOCK | VB3 | 366] = {"@Item Blocks/VB3/Powerup Block #1"},
    [BLOCK | VB3 | 367] = {"@Item Blocks/VB3/Powerup Block #2"},
    [BLOCK | VBH | 368] = {"@P-Switch Blocks/VBH/P-Switch Coin Block #1"},
    [BLOCK | VBH | 369] = {"@Coin Blocks/VBH/Multi Coin Block #1"},
    [BLOCK | VBH | 370] = {"@Item Blocks/VBH/Powerup Block #1"},
    [BLOCK | VBH | 371] = {"@Item Blocks/VBH/Directional Coin Block #1"},
    [BLOCK | VB2 | 372] = {"@Item Blocks/VB2/Powerup Block #1"},
    [BLOCK | VB2 | 373] = {"@Yellow Switch Blocks/VB2/Yellow Switch Palace Block #1"},
    [BLOCK | VB2 | 374] = {"@Item Blocks/VB2/Powerup Block #2"},
    [BLOCK | VB2 | 375] = {"@Item Blocks/VB2/Wings Block #1"},
    [BLOCK | VB1 | 376] = {"@Green Switch Blocks/VB1/Green Switch Palace Block #1"},
    [BLOCK | VB1 | 377] = {"@Invisible Blocks/VB1/Invisible Coin Block #1"},
    [BLOCK | VB1 | 378] = {"@Invisible Blocks/VB1/Invisible Coin Block #2"},
    [BLOCK | VB1 | 379] = {"@Invisible Blocks/VB1/Invisible Coin Block #3"},
    [BLOCK | VB1 | 380] = {"@Yellow Switch Blocks/VB1/Yellow Switch Palace Block #1"},
    [BLOCK | VB1 | 381] = {"@Yellow Switch Blocks/VB1/Yellow Switch Palace Block #2"},
    [BLOCK | VB1 | 382] = {"@Yellow Switch Blocks/VB1/Yellow Switch Palace Block #3"},
    [BLOCK | VB1 | 383] = {"@Yellow Switch Blocks/VB1/Yellow Switch Palace Block #4"},
    [BLOCK | VB1 | 384] = {"@Item Blocks/VB1/Vine Block #1"},
    [BLOCK | CSA | 385] = {"@Item Blocks/CSA/Powerup Block #1"},
    [BLOCK | CSA | 386] = {"@Item Blocks/CSA/Powerup Block #2"},
    [BLOCK | VD2 | 387] = {"@Coin Blocks/VD2/Coin Block #1"},
    [BLOCK | VD2 | 388] = {"@Item Blocks/VD2/Powerup Block #1"},
    [BLOCK | VD2 | 389] = {"@Coin Blocks/VD2/Coin Block #2"},
    [BLOCK | VD2 | 390] = {"@Coin Blocks/VD2/Coin Block #3"},
    [BLOCK | VD2 | 391] = {"@Item Blocks/VD2/Vine Block #1"},
    [BLOCK | VD2 | 392] = {"@Invisible Blocks/VD2/Invisible 1-Up Mushroom Block #1"},
    [BLOCK | VD2 | 393] = {"@Coin Blocks/VD2/Coin Block #4"},
    [BLOCK | VD2 | 394] = {"@Coin Blocks/VD2/Coin Block #5"},
    [BLOCK | VD2 | 395] = {"@Item Blocks/VD2/Powerup Block #2"},
    [BLOCK | VD2 | 396] = {"@Item Blocks/VD2/Powerup Block #3"},
    [BLOCK | VD2 | 397] = {"@Item Blocks/VD2/Powerup Block #4"},
    [BLOCK | VD2 | 398] = {"@Item Blocks/VD2/Powerup Block #5"},
    [BLOCK | VD2 | 399] = {"@Coin Blocks/VD2/Multi Coin Block #1"},
    [BLOCK | VD2 | 400] = {"@Coin Blocks/VD2/Multi Coin Block #2"},
    [BLOCK | VD4 | 401] = {"@Item Blocks/VD4/Powerup Block #1"},
    [BLOCK | VD4 | 402] = {"@Item Blocks/VD4/Powerup Block #2"},
    [BLOCK | VD4 | 403] = {"@Coin Blocks/VD4/Coin Block #1"},
    [BLOCK | VD4 | 404] = {"@Coin Blocks/VD4/Coin Block #2"},
    [BLOCK | VD4 | 405] = {"@Coin Blocks/VD4/Coin Block #3"},
    [BLOCK | VD4 | 406] = {"@Item Blocks/VD4/1-Up Mushroom Block #1"},
    [BLOCK | VD4 | 407] = {"@Coin Blocks/VD4/Coin Block #4"},
    [BLOCK | VD4 | 408] = {"@Coin Blocks/VD4/Coin Block #5"},
    [BLOCK | VD4 | 409] = {"@Coin Blocks/VD4/Coin Block #6"},
    [BLOCK | VD4 | 410] = {"@Coin Blocks/VD4/Coin Block #7"},
    [BLOCK | VD4 | 411] = {"@Coin Blocks/VD4/Coin Block #8"},
    [BLOCK | VD1 | 412] = {"@Flying Blocks/VD1/Flying Question Block #1"},
    [BLOCK | VD1 | 413] = {"@Item Blocks/VD1/Powerup Block #1"},
    [BLOCK | VD1 | 414] = {"@Item Blocks/VD1/Powerup Block #2"},
    [BLOCK | VD1 | 415] = {"@Coin Blocks/VD1/Coin Block #1"},
    [BLOCK | VD1 | 416] = {"@Item Blocks/VD1/1-Up Mushroom Block #1"},
    [BLOCK | VD1 | 417] = {"@Item Blocks/VD1/Powerup Block #3"},
    [BLOCK | VD1 | 418] = {"@Item Blocks/VD1/Vine Block #1"},
    [BLOCK | VD1 | 419] = {"@Item Blocks/VD1/Star Block #1"},
    [BLOCK | VD1 | 420] = {"@Item Blocks/VD1/Powerup Block #4"},
    [BLOCK | VD1 | 421] = {"@Coin Blocks/VD1/Coin Block #2"},
    [BLOCK | VDC | 422] = {"@Item Blocks/VDC/1-Up Mushroom Block #1"},
    [BLOCK | VDC | 423] = {"@Item Blocks/VDC/1-Up Mushroom Block #2"},
    [BLOCK | VDC | 424] = {"@Item Blocks/VDC/Powerup Block #1"},
    [BLOCK | VDC | 425] = {"@Item Blocks/VDC/1-Up Mushroom Block #3"},
    [BLOCK | VDC | 426] = {"@Green Switch Blocks/VDC/Green Switch Palace Block #1"},
    [BLOCK | FGH | 427] = {"@Coin Blocks/FGH/Coin Block #1"},
    [BLOCK | FGH | 428] = {"@Item Blocks/FGH/Powerup Block #1"},
    [BLOCK | FGH | 429] = {"@Flying Blocks/FGH/Flying Question Block #1"},
    [BLOCK | FGH | 430] = {"@Item Blocks/FGH/Powerup Block #2"},
    [BLOCK | FGH | 431] = {"@Item Blocks/FGH/1-Up Mushroom Block #1"},
    [BLOCK | FI1 | 432] = {"@Item Blocks/FI1/Powerup Block #1"},
    [BLOCK | FI1 | 433] = {"@Item Blocks/FI1/Yoshi Block #1"},
    [BLOCK | FI1 | 434] = {"@Item Blocks/FI1/Powerup Block #2"},
    [BLOCK | FI1 | 435] = {"@Item Blocks/FI1/Key Block #1"},
    [BLOCK | FI1 | 436] = {"@Item Blocks/FI1/1-Up Mushroom Block #1"},
    [BLOCK | FI4 | 437] = {"@Coin Blocks/FI4/Multi Coin Block #1"},
    [BLOCK | FI4 | 438] = {"@Coin Blocks/FI4/Coin Block #1"},
    [BLOCK | FI4 | 439] = {"@Coin Blocks/FI4/Coin Block #2"},
    [BLOCK | FI4 | 440] = {"@Coin Blocks/FI4/Coin Block #3"},
    [BLOCK | FI4 | 441] = {"@Coin Blocks/FI4/Coin Block #4"},
    [BLOCK | FI4 | 442] = {"@Item Blocks/FI4/Powerup Block #1"},
    [BLOCK | FI4 | 443] = {"@Coin Blocks/FI4/Coin Block #5"},
    [BLOCK | FI4 | 444] = {"@Coin Blocks/FI4/Coin Block #6"},
    [BLOCK | FI4 | 445] = {"@Coin Blocks/FI4/Coin Block #7"},
    [BLOCK | FI4 | 446] = {"@Item Blocks/FI4/Powerup Block #2"},
    [BLOCK | FI4 | 447] = {"@Coin Blocks/FI4/Coin Block #8"},
    [BLOCK | FI4 | 448] = {"@Coin Blocks/FI4/Coin Block #9"},
    [BLOCK | FI4 | 449] = {"@Coin Blocks/FI4/Coin Block #10"},
    [BLOCK | FI2 | 450] = {"@Green Switch Blocks/FI2/Green Switch Palace Block #1"},
    [BLOCK | FI2 | 451] = {"@Item Blocks/FI2/Powerup Block #1"},
    [BLOCK | FI2 | 452] = {"@Invisible Blocks/FI2/Invisible Coin Block #1"},
    [BLOCK | FI2 | 453] = {"@Invisible Blocks/FI2/Invisible Coin Block #2"},
    [BLOCK | FI2 | 454] = {"@Invisible Blocks/FI2/Invisible 1-Up Mushroom Block #1"},
    [BLOCK | FI2 | 455] = {"@Invisible Blocks/FI2/Invisible Coin Block #3"},
    [BLOCK | FI2 | 456] = {"@Yellow Switch Blocks/FI2/Yellow Switch Palace Block #1"},
    [BLOCK | FSA | 457] = {"@Item Blocks/FSA/Powerup Block #1"},
    [BLOCK | FSA | 458] = {"@Item Blocks/FSA/Powerup Block #2"},
    [BLOCK | FSA | 459] = {"@Item Blocks/FSA/1-Up Mushroom Block #1"},
    [BLOCK | FI3 | 460] = {"@Item Blocks/FI3/Yoshi Block #1"},
    [BLOCK | FI3 | 461] = {"@Coin Blocks/FI3/Coin Block #1"},
    [BLOCK | FI3 | 462] = {"@Coin Blocks/FI3/Multi Coin Block #1"},
    [BLOCK | FI3 | 463] = {"@Coin Blocks/FI3/Coin Block #2"},
    [BLOCK | FI3 | 464] = {"@Coin Blocks/FI3/Multi Coin Block #2"},
    [BLOCK | FI3 | 465] = {"@Coin Blocks/FI3/Coin Block #3"},
    [BLOCK | FI3 | 466] = {"@Coin Blocks/FI3/Coin Block #4"},
    [BLOCK | FI3 | 467] = {"@Coin Blocks/FI3/Coin Block #5"},
    [BLOCK | FI3 | 468] = {"@Coin Blocks/FI3/Coin Block #6"},
    [BLOCK | FI3 | 469] = {"@Coin Blocks/FI3/Coin Block #7"},
    [BLOCK | FI3 | 470] = {"@Coin Blocks/FI3/Coin Block #8"},
    [BLOCK | FI3 | 471] = {"@Coin Blocks/FI3/Coin Block #9"},
    [BLOCK | FI3 | 472] = {"@Coin Blocks/FI3/Coin Block #10"},
    [BLOCK | FI3 | 473] = {"@Coin Blocks/FI3/Coin Block #11"},
    [BLOCK | FI3 | 474] = {"@Coin Blocks/FI3/Coin Block #12"},
    [BLOCK | FI3 | 475] = {"@Coin Blocks/FI3/Coin Block #13"},
    [BLOCK | FI3 | 476] = {"@Coin Blocks/FI3/Coin Block #14"},
    [BLOCK | FI3 | 477] = {"@Coin Blocks/FI3/Coin Block #15"},
    [BLOCK | FI3 | 478] = {"@Coin Blocks/FI3/Coin Block #16"},
    [BLOCK | FI3 | 479] = {"@Coin Blocks/FI3/Coin Block #17"},
    [BLOCK | FI3 | 480] = {"@Coin Blocks/FI3/Coin Block #18"},
    [BLOCK | FI3 | 481] = {"@Coin Blocks/FI3/Coin Block #19"},
    [BLOCK | FI3 | 482] = {"@Coin Blocks/FI3/Coin Block #20"},
    [BLOCK | FI3 | 483] = {"@Coin Blocks/FI3/Coin Block #21"},
    [BLOCK | FI3 | 484] = {"@Coin Blocks/FI3/Coin Block #22"},
    [BLOCK | FI3 | 485] = {"@Coin Blocks/FI3/Coin Block #23"},
    [BLOCK | FI3 | 486] = {"@Coin Blocks/FI3/Coin Block #24"},
    [BLOCK | SZ8 | 487] = {"@Item Blocks/SZ8/Yoshi Block #1"},
    [BLOCK | SZ8 | 488] = {"@Coin Blocks/SZ8/Coin Block #1"},
    [BLOCK | SZ8 | 489] = {"@Coin Blocks/SZ8/Coin Block #2"},
    [BLOCK | SZ8 | 490] = {"@Coin Blocks/SZ8/Coin Block #3"},
    [BLOCK | SZ8 | 491] = {"@Coin Blocks/SZ8/Coin Block #4"},
    [BLOCK | SZ8 | 492] = {"@Coin Blocks/SZ8/Coin Block #5"},
    [BLOCK | SZ8 | 493] = {"@Item Blocks/SZ8/Blue P-Switch Block #1"},
    [BLOCK | SZ8 | 494] = {"@Item Blocks/SZ8/Powerup Block #1"},
    [BLOCK | SZ8 | 495] = {"@Item Blocks/SZ8/Star Block #1"},
    [BLOCK | SZ8 | 496] = {"@Coin Blocks/SZ8/Coin Block #6"},
    [BLOCK | SZ8 | 497] = {"@Coin Blocks/SZ8/Coin Block #7"},
    [BLOCK | SZ8 | 498] = {"@Coin Blocks/SZ8/Coin Block #8"},
    [BLOCK | SZ8 | 499] = {"@Coin Blocks/SZ8/Coin Block #9"},
    [BLOCK | SZ8 | 500] = {"@Coin Blocks/SZ8/Coin Block #10"},
    [BLOCK | SZ8 | 501] = {"@Coin Blocks/SZ8/Coin Block #11"},
    [BLOCK | SZ8 | 502] = {"@Coin Blocks/SZ8/Coin Block #12"},
    [BLOCK | SZ8 | 503] = {"@Coin Blocks/SZ8/Coin Block #13"},
    [BLOCK | SZ8 | 504] = {"@Coin Blocks/SZ8/Coin Block #14"},
    [BLOCK | SZ8 | 505] = {"@Coin Blocks/SZ8/Coin Block #15"},
    [BLOCK | SZ8 | 506] = {"@Coin Blocks/SZ8/Coin Block #16"},
    [BLOCK | SZ8 | 507] = {"@Coin Blocks/SZ8/Coin Block #17"},
    [BLOCK | SZ8 | 508] = {"@Coin Blocks/SZ8/Coin Block #18"},
    [BLOCK | SZ8 | 509] = {"@Coin Blocks/SZ8/Multi Coin Block #1"},
    [BLOCK | SZ8 | 510] = {"@Coin Blocks/SZ8/Coin Block #19"},
    [BLOCK | SZ8 | 511] = {"@Coin Blocks/SZ8/Coin Block #20"},
    [BLOCK | SZ8 | 512] = {"@Coin Blocks/SZ8/Coin Block #21"},
    [BLOCK | SZ8 | 513] = {"@Coin Blocks/SZ8/Coin Block #22"},
    [BLOCK | SZ8 | 514] = {"@Coin Blocks/SZ8/Coin Block #23"},
    [BLOCK | SZ8 | 515] = {"@Item Blocks/SZ8/Powerup Block #2"},
    [BLOCK | SZ8 | 516] = {"@Flying Blocks/SZ8/Flying Question Block #1"},
    [BLOCK | SZ7 | 517] = {"@Item Blocks/SZ7/Powerup Block #1"},
    [BLOCK | SZ7 | 518] = {"@Item Blocks/SZ7/Yoshi Block #1"},
    [BLOCK | SZ7 | 519] = {"@Coin Blocks/SZ7/Coin Block #1"},
    [BLOCK | SZ7 | 520] = {"@Item Blocks/SZ7/Powerup Block #2"},
    [BLOCK | SZ7 | 521] = {"@Coin Blocks/SZ7/Coin Block #2"},
    [BLOCK | SZ6 | 522] = {"@Item Blocks/SZ6/Powerup Block #1"},
    [BLOCK | SZ6 | 523] = {"@Coin Blocks/SZ6/Coin Block #1"},
    [BLOCK | SZ6 | 524] = {"@Coin Blocks/SZ6/Coin Block #2"},
    [BLOCK | SZ6 | 525] = {"@Item Blocks/SZ6/Yoshi Block #1"},
    [BLOCK | SZ6 | 526] = {"@Item Blocks/SZ6/1-Up Mushroom Block #1"},
    [BLOCK | SZ6 | 527] = {"@Coin Blocks/SZ6/Multi Coin Block #1"},
    [BLOCK | SZ6 | 528] = {"@Coin Blocks/SZ6/Coin Block #3"},
    [BLOCK | SZ6 | 529] = {"@Coin Blocks/SZ6/Coin Block #4"},
    [BLOCK | SZ6 | 530] = {"@Coin Blocks/SZ6/Coin Block #5"},
    [BLOCK | SZ6 | 531] = {"@Coin Blocks/SZ6/Coin Block #6"},
    [BLOCK | SZ6 | 532] = {"@Coin Blocks/SZ6/Coin Block #7"},
    [BLOCK | SZ6 | 533] = {"@Coin Blocks/SZ6/Coin Block #8"},
    [BLOCK | SZ6 | 534] = {"@Coin Blocks/SZ6/Coin Block #9"},
    [BLOCK | SZ6 | 535] = {"@Coin Blocks/SZ6/Coin Block #10"},
    [BLOCK | SZ6 | 536] = {"@Coin Blocks/SZ6/Coin Block #11"},
    [BLOCK | SZ6 | 537] = {"@Coin Blocks/SZ6/Coin Block #12"},
    [BLOCK | SZ6 | 538] = {"@Coin Blocks/SZ6/Coin Block #13"},
    [BLOCK | SZ6 | 539] = {"@Coin Blocks/SZ6/Coin Block #14"},
    [BLOCK | SZ6 | 540] = {"@Coin Blocks/SZ6/Coin Block #15"},
    [BLOCK | SZ6 | 541] = {"@Coin Blocks/SZ6/Coin Block #16"},
    [BLOCK | SZ6 | 542] = {"@Coin Blocks/SZ6/Coin Block #17"},
    [BLOCK | SZ6 | 543] = {"@Coin Blocks/SZ6/Coin Block #18"},
    [BLOCK | SZ6 | 544] = {"@Coin Blocks/SZ6/Coin Block #19"},
    [BLOCK | SZ6 | 545] = {"@Coin Blocks/SZ6/Coin Block #20"},
    [BLOCK | SZ6 | 546] = {"@Coin Blocks/SZ6/Coin Block #21"},
    [BLOCK | SZ6 | 547] = {"@Coin Blocks/SZ6/Coin Block #22"},
    [BLOCK | SZ6 | 548] = {"@Coin Blocks/SZ6/Coin Block #23"},
    [BLOCK | SZ6 | 549] = {"@Coin Blocks/SZ6/Coin Block #24"},
    [BLOCK | SZ6 | 550] = {"@Coin Blocks/SZ6/Coin Block #25"},
    [BLOCK | SZ6 | 551] = {"@Coin Blocks/SZ6/Coin Block #26"},
    [BLOCK | SZ6 | 552] = {"@Coin Blocks/SZ6/Coin Block #27"},
    [BLOCK | SZ6 | 553] = {"@Coin Blocks/SZ6/Coin Block #28"},
    [BLOCK | SZ6 | 554] = {"@Item Blocks/SZ6/Powerup Block #2"},
    [BLOCK | SZ6 | 555] = {"@Coin Blocks/SZ6/Coin Block #29"},
    [BLOCK | SZ6 | 556] = {"@Coin Blocks/SZ6/Coin Block #30"},
    [BLOCK | SZ6 | 557] = {"@Coin Blocks/SZ6/Coin Block #31"},
    [BLOCK | SZ6 | 558] = {"@Coin Blocks/SZ6/Coin Block #32"},
    [BLOCK | SZ6 | 559] = {"@Coin Blocks/SZ6/Coin Block #33"},
    [BLOCK | SZ5 | 560] = {"@Item Blocks/SZ5/Yoshi Block #1"},
    [BLOCK | SZ1 | 561] = {"@Item Blocks/SZ1/Vine Block #1"},
    [BLOCK | SZ1 | 562] = {"@Item Blocks/SZ1/Vine Block #2"},
    [BLOCK | SZ1 | 563] = {"@Item Blocks/SZ1/Vine Block #3"},
    [BLOCK | SZ1 | 564] = {"@Item Blocks/SZ1/Vine Block #4"},
    [BLOCK | SZ1 | 565] = {"@Item Blocks/SZ1/1-Up Mushroom Block #1"},
    [BLOCK | SZ1 | 566] = {"@Item Blocks/SZ1/Vine Block #5"},
    [BLOCK | SZ1 | 567] = {"@Item Blocks/SZ1/Blue P-Switch Block #1"},
    [BLOCK | SZ1 | 568] = {"@Item Blocks/SZ1/Vine Block #6"},
    [BLOCK | SZ1 | 569] = {"@Item Blocks/SZ1/Powerup Block #1"},
    [BLOCK | SZ1 | 570] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #1"},
    [BLOCK | SZ1 | 571] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #2"},
    [BLOCK | SZ1 | 572] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #3"},
    [BLOCK | SZ1 | 573] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #4"},
    [BLOCK | SZ1 | 574] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #5"},
    [BLOCK | SZ1 | 575] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #6"},
    [BLOCK | SZ1 | 576] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #7"},
    [BLOCK | SZ1 | 577] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #8"},
    [BLOCK | SZ1 | 578] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #9"},
    [BLOCK | SZ1 | 579] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #10"},
    [BLOCK | SZ1 | 580] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #11"},
    [BLOCK | SZ1 | 581] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #12"},
    [BLOCK | SZ1 | 582] = {"@P-Switch Blocks/SZ1/P-Switch Coin Block #13"},
    [BLOCK | SZ2 | 583] = {"@Item Blocks/SZ2/Powerup Block #1"},
    [BLOCK | SZ2 | 584] = {"@Coin Blocks/SZ2/Coin Block #1"},
    [BLOCK | SZ2 | 585] = {"@Coin Blocks/SZ2/Coin Block #2"},
    [BLOCK | SZ2 | 586] = {"@Item Blocks/SZ2/Powerup Block #2"},
    [BLOCK | SZ2 | 587] = {"@Coin Blocks/SZ2/Coin Block #3"},
    [BLOCK | SZ2 | 588] = {"@Coin Blocks/SZ2/Coin Block #4"},
    [BLOCK | SZ2 | 589] = {"@Item Blocks/SZ2/Powerup Block #3"},
    [BLOCK | SZ2 | 590] = {"@Coin Blocks/SZ2/Multi Coin Block #1"},
    [BLOCK | SZ2 | 591] = {"@Coin Blocks/SZ2/Coin Block #5"},
    [BLOCK | SZ2 | 592] = {"@Coin Blocks/SZ2/Coin Block #6"},
    [BLOCK | SZ3 | 593] = {"@Item Blocks/SZ3/Powerup Block #1"},
    [BLOCK | SZ3 | 594] = {"@Item Blocks/SZ3/Yoshi Block #1"},
    [BLOCK | SZ3 | 595] = {"@Item Blocks/SZ3/Wings Block #1"},
    [BLOCK | SZ4 | 596] = {"@Item Blocks/SZ4/Powerup Block #1"},
    [BLOCK | SZ4 | 597] = {"@Item Blocks/SZ4/Star Block #1"},
    [BLOCK | SR2 | 598] = {"@Item Blocks/SR2/Star Block #1"},
    [BLOCK | SR3 | 599] = {"@Item Blocks/SR3/Key Block #1"},
    [BLOCK | SR4 | 600] = {"@Item Blocks/SR4/Powerup Block #1"},
    [BLOCK | SR4 | 601] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #1"},
    [BLOCK | SR4 | 602] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #2"},
    [BLOCK | SR4 | 603] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #3"},
    [BLOCK | SR4 | 604] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #4"},
    [BLOCK | SR4 | 605] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #5"},
    [BLOCK | SR4 | 606] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #6"},
    [BLOCK | SR4 | 607] = {"@Green Switch Blocks/SR4/Green Switch Palace Block #7"},
    [BLOCK | SR4 | 608] = {"@Item Blocks/SR4/Key Block #1"},
    [BLOCK | SR5 | 609] = {"@Item Blocks/SR5/Directional Coin Block #1"},
    [BLOCK | SR5 | 610] = {"@Item Blocks/SR5/1-Up Mushroom Block #1"},
    [BLOCK | SR5 | 611] = {"@Item Blocks/SR5/Vine Block #1"},
    [BLOCK | SR5 | 612] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #1"},
    [BLOCK | SR5 | 613] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #2"},
    [BLOCK | SR5 | 614] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #3"},
    [BLOCK | SR5 | 615] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #4"},
    [BLOCK | SR5 | 616] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #5"},
    [BLOCK | SR5 | 617] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #6"},
    [BLOCK | SR5 | 618] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #7"},
    [BLOCK | SR5 | 619] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #8"},
    [BLOCK | SR5 | 620] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #9"},
    [BLOCK | SR5 | 621] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #10"},
    [BLOCK | SR5 | 622] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #11"},
    [BLOCK | SR5 | 623] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #12"},
    [BLOCK | SR5 | 624] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #13"},
    [BLOCK | SR5 | 625] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #14"},
    [BLOCK | SR5 | 626] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #15"},
    [BLOCK | SR5 | 627] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #16"},
    [BLOCK | SR5 | 628] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #17"},
    [BLOCK | SR5 | 629] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #18"},
    [BLOCK | SR5 | 630] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #19"},
    [BLOCK | SR5 | 631] = {"@Yellow Switch Blocks/SR5/Yellow Switch Palace Block #20"},
    [BLOCK | SR5 | 632] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #1"},
    [BLOCK | SR5 | 633] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #2"},
    [BLOCK | SR5 | 634] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #3"},
    [BLOCK | SR5 | 635] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #4"},
    [BLOCK | SR5 | 636] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #5"},
    [BLOCK | SR5 | 637] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #6"},
    [BLOCK | SR5 | 638] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #7"},
    [BLOCK | SR5 | 639] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #8"},
    [BLOCK | SR5 | 640] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #9"},
    [BLOCK | SR5 | 641] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #10"},
    [BLOCK | SR5 | 642] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #11"},
    [BLOCK | SR5 | 643] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #12"},
    [BLOCK | SR5 | 644] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #13"},
    [BLOCK | SR5 | 645] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #14"},
    [BLOCK | SR5 | 646] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #15"},
    [BLOCK | SR5 | 647] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #16"},
    [BLOCK | SR5 | 648] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #17"},
    [BLOCK | SR5 | 649] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #18"},
    [BLOCK | SR5 | 650] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #19"},
    [BLOCK | SR5 | 651] = {"@Green Switch Blocks/SR5/Green Switch Palace Block #20"},
  

}